{
  "compatibilityLevel": 1570,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"CapacityID\",\"UTC_offset\",\"TimePoint2\",\"TimePoint\",\"fnGetData\",\"TimePoints2\",\"MetricsByItemandDay\",\"MetricsByItemandHour\",\"MetricsByItemandOperationandHour\",\"TimePoints\",\"CUDetail\",\"TimePointCUDetail\",\"TimePoint2CUDetail\",\"TimePointInteractiveDetail\",\"TimePoint2InteractiveDetail\",\"TimePointBackgroundDetail\",\"TimePoint2BackgroundDetail\",\"Capacities\",\"Workspaces\",\"Items\",\"All Measures\",\"Metrics\",\"MaxMemoryByItem\",\"Performance2daySnapshot\",\"MetricsByItemandOperationandDay\",\"MetricsByItem\",\"OperationNames\",\"MetricsByItemandOperation\",\"ItemKind\",\"StorageByWorkspaces\",\"StorageByWorkspacesandDay\",\"StorageByWorkspacesandHour\",\"TimePointOverageDetail\",\"TimePointOveragesByWorkloads\",\"TimePoint2OveragesByWorkloads\",\"Dates\",\"OperationForStorage\",\"Workloads\",\"Billing type\",\"WorkloadForStorage\",\"SystemEvents\",\"MaxMemoryByItemAndHour\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.127.1235.0 (24.03)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "CapacityID",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "description": "An ID of a capacity you're an admin of",
        "expression": "\"DAD6DE05-202F-438E-9685-B67D69D24255\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "7c28a00e-a701-4617-864b-2e5ea88fc4e9",
        "parameterValuesColumn": {
          "column": "capacityId",
          "table": "Capacities"
        },
        "queryGroup": "Parameters (Connections)"
      },
      {
        "name": "UTC_offset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": [
          "Numerical values ranging from 14 to -12.",
          "To signify a Half hour timezone, use .5. For example, for Iran's standard time enter 3.5."
        ],
        "expression": "\"0\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "fca86e1e-1aaf-4a85-bbff-46fdb3a3aea5",
        "queryGroup": "Parameters (Connections)"
      },
      {
        "name": "TimePoint",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "description": "Automatically populated",
        "expression": "#datetime(2021, 1, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "54b1f064-6db0-4561-b1a8-057146b3e422",
        "parameterValuesColumn": {
          "column": "TimePoint",
          "table": "TimePoints"
        },
        "queryGroup": "Parameters (Connections)"
      },
      {
        "name": "fnGetData",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (KustoFunctionName as text, optional xCapacity_ID as text,optional Timepoint as datetime,optional agoDays as text) => ",
          "    let",
          "     ",
          "",
          "        Source = CapacityMetricsCES.GetMetricsData(",
          "            KustoFunctionName , ",
          "            if xCapacity_ID = null then CapacityID else xCapacity_ID , ",
          "            //\"A03400B4-817C-462B-A146-522324A4AF2A\",",
          "            \"7E4058F3-1C1F-4C3A-8151-03D3A2C3C30C\",",
          "            if agoDays = null then \"13\" else agoDays, ",
          "            //\"https://pbipinternal.kusto.windows.net\",",
          "            \"https://pbipam.kusto.windows.net\",  ",
          "            \"pbip\",",
          "            Number.FromText( UTC_offset ),",
          "            null,",
          "            DateTime.ToText(Timepoint)",
          "            )",
          "        in",
          "            Source",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "2b730c75-851e-41b7-8565-e27f41f72863",
        "queryGroup": "Functions\\fnGet"
      },
      {
        "name": "TimePoint2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "description": "Automatically populated",
        "expression": "#datetime(2021, 1, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "465e6fc3-32fe-403c-847e-e352de268bf3",
        "parameterValuesColumn": {
          "column": "TimePoint",
          "table": "TimePoints2"
        },
        "queryGroup": "Parameters (Connections)"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters (Connections)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Functions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Direct Query"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Direct Query\\TimePoint2"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Direct Query\\Timepoint"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "folder": "Direct Query\\Performance"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "11"
          }
        ],
        "folder": "Capacity"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Direct Query\\Metrics Preview"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Functions\\fnGet"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "9"
          }
        ],
        "folder": "Onelake"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "10"
          }
        ],
        "folder": "CarryOver"
      }
    ],
    "relationships": [
      {
        "name": "cde124c5-d2c0-4ae0-8c4b-9411ef43e9f0",
        "fromColumn": "WindowStartTime",
        "fromTable": "TimePointCUDetail",
        "toColumn": "TimePoint",
        "toTable": "TimePoints2"
      },
      {
        "name": "65457602-3df3-4972-80a3-07056a74d1ea",
        "fromColumn": "capacityId",
        "fromTable": "Items",
        "toColumn": "capacityId",
        "toTable": "Capacities"
      },
      {
        "name": "0564a155-1c8c-43b5-a57b-31f1a6e18bfb",
        "fromColumn": "OperationName",
        "fromTable": "MetricsByItemandOperationandHour",
        "toColumn": "OperationName",
        "toTable": "OperationNames"
      },
      {
        "name": "696ba4f4-005f-46c3-b842-7e6c2137b86e",
        "fromColumn": "OperationName",
        "fromTable": "MetricsByItemandOperationandDay",
        "toColumn": "OperationName",
        "toTable": "OperationNames"
      },
      {
        "name": "5c5508e9-e1cf-46c8-81c9-16ac2cf5d92b",
        "fromColumn": "OperationName",
        "fromTable": "MetricsByItemandOperation",
        "toColumn": "OperationName",
        "toTable": "OperationNames"
      },
      {
        "name": "18047a34-4aaf-4197-a7fa-8d9cdc0df960",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ItemKind",
        "fromTable": "ItemKind",
        "toCardinality": "many",
        "toColumn": "ItemKind",
        "toTable": "Items"
      },
      {
        "name": "f872320f-a18f-40d2-912b-47b88c800b89",
        "fromColumn": "WorkspaceKey",
        "fromTable": "StorageByWorkspacesandDay",
        "toColumn": "WorkspaceKey",
        "toTable": "Workspaces"
      },
      {
        "name": "ce5455a9-e019-449d-82e0-529d64686443",
        "fromColumn": "WorkspaceKey",
        "fromTable": "StorageByWorkspacesandHour",
        "toColumn": "WorkspaceKey",
        "toTable": "Workspaces"
      },
      {
        "name": "3f691c9e-578d-4928-b816-5f8773e18df7",
        "fromColumn": "WorkspaceKey",
        "fromTable": "StorageByWorkspaces",
        "toColumn": "WorkspaceKey",
        "toTable": "Workspaces"
      },
      {
        "name": "2da66da5-215c-4834-b1b1-2073f10249bc",
        "fromColumn": "WindowStartTime",
        "fromTable": "CUDetail",
        "toColumn": "TimePoint",
        "toTable": "TimePoints"
      },
      {
        "name": "59558d05-8dec-4bcf-8838-92a75487bd2a",
        "fromColumn": "WindowStartTime",
        "fromTable": "TimePointOverageDetail",
        "toColumn": "TimePoint",
        "toTable": "TimePoints"
      },
      {
        "name": "4d7573d6-00f4-4f51-9091-32db817bd0c2",
        "fromColumn": "PremiumCapacityId",
        "fromTable": "Workspaces",
        "toColumn": "capacityId",
        "toTable": "Capacities"
      },
      {
        "name": "e9b929fe-50c9-6ac1-2fb1-9e0e7f39501a",
        "fromColumn": "WindowStartTime",
        "fromTable": "TimePointOveragesByWorkloads",
        "toColumn": "TimePoint",
        "toTable": "TimePoints2"
      },
      {
        "name": "8c9364c3-551a-6ca1-6702-f1beef1a5395",
        "fromColumn": "WindowStartTime",
        "fromTable": "TimePoint2OveragesByWorkloads",
        "toColumn": "TimePoint",
        "toTable": "TimePoints"
      },
      {
        "name": "13e8076e-6bac-4096-8231-502c24955024",
        "fromColumn": "DateTime",
        "fromTable": "MetricsByItemandHour",
        "toColumn": "Hour Start",
        "toTable": "DateTime"
      },
      {
        "name": "d449b194-df1f-4e12-a8a9-916dcb4034b6",
        "fromColumn": "DateTime",
        "fromTable": "MetricsByItemandOperationandHour",
        "toColumn": "Hour Start",
        "toTable": "DateTime"
      },
      {
        "name": "37d37e84-7494-4023-80fd-d13ea2bdc74f",
        "fromColumn": "DateTime",
        "fromTable": "StorageByWorkspacesandHour",
        "toColumn": "Hour Start",
        "toTable": "DateTime"
      },
      {
        "name": "ac0000b7-0398-404e-afc1-6ca955ed9da3",
        "fromColumn": "Date",
        "fromTable": "StorageByWorkspacesandDay",
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "61c008ad-3a45-4f2e-87e9-0171fb9897e2",
        "fromColumn": "Date",
        "fromTable": "DateTime",
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "0c597e6a-4026-4f4b-9a7a-9746bf050fdd",
        "fromColumn": "Date",
        "fromTable": "MetricsByItemandOperationandDay",
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "fab4fe39-d682-4e84-bcf2-d5f43acd5b57",
        "fromColumn": "Date",
        "fromTable": "MetricsByItemandDay",
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "b632f052-7fd0-4a56-b906-60e1b08ffaf6",
        "fromColumn": "WorkloadKind",
        "fromTable": "StorageByWorkspacesandDay",
        "toColumn": "WorkloadKind",
        "toTable": "Workloads"
      },
      {
        "name": "9ab16224-68c9-4447-9fb8-ecaa04ccb845",
        "fromColumn": "WorkloadKind",
        "fromTable": "StorageByWorkspacesandHour",
        "toColumn": "WorkloadKind",
        "toTable": "Workloads"
      },
      {
        "name": "19ddf7d8-05cb-495d-83e7-200e636fb4f9",
        "fromColumn": "OperationName",
        "fromTable": "StorageByWorkspacesandDay",
        "toColumn": "OperationName",
        "toTable": "OperationForStorage"
      },
      {
        "name": "d12f0533-45ea-4a6a-a19c-7dd72e99f28d",
        "fromColumn": "OperationName",
        "fromTable": "StorageByWorkspacesandHour",
        "toColumn": "OperationName",
        "toTable": "OperationForStorage"
      },
      {
        "name": "f2f0c743-2ef8-411c-be48-e987af870de6",
        "fromColumn": "Billing type",
        "fromTable": "StorageByWorkspacesandHour",
        "toColumn": "Billing type",
        "toTable": "Billing type"
      },
      {
        "name": "de680cf4-fccd-4f9b-b033-c142693f0718",
        "fromColumn": "Billing type",
        "fromTable": "StorageByWorkspacesandDay",
        "toColumn": "Billing type",
        "toTable": "Billing type"
      },
      {
        "name": "d1ff05cb-3277-4a02-8659-28a0b28be534",
        "fromColumn": "BinnedCapacityStateTransitionTime",
        "fromTable": "SystemEvents",
        "toColumn": "TimePoint",
        "toTable": "TimePoints"
      },
      {
        "name": "7da2bcbe-50b6-4ac5-86c9-cdb80fec651b",
        "fromColumn": "WindowStartTime",
        "fromTable": "CUDetail",
        "toColumn": "TimePoint",
        "toTable": "TimePoints2"
      },
      {
        "name": "5841844f-e48e-4b5f-b578-095da141b703",
        "fromColumn": "WindowStartTime",
        "fromTable": "TimePoint2CUDetail",
        "toColumn": "TimePoint",
        "toTable": "TimePoints"
      },
      {
        "name": "285b6496-3f9e-47f5-94ea-10b0aa27385b",
        "fromColumn": "Dynamic Columns",
        "fromTable": "Dynamic Columns",
        "toCardinality": "many",
        "toColumn": "Measure",
        "toTable": "ItemKind"
      },
      {
        "name": "678c19df-ffd0-7e95-2559-bec17164eacd",
        "fromColumn": "UniqueKey",
        "fromTable": "TimePointBackgroundDetail",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "2f952bd3-2592-1329-6d25-b479d8e5e985",
        "fromColumn": "UniqueKey",
        "fromTable": "TimePointInteractiveDetail",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "f3cb1f56-22a0-b644-5ba6-2696500b06d9",
        "fromColumn": "UniqueKey",
        "fromTable": "TimePoint2InteractiveDetail",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "ad4b7d90-c128-4975-aef5-a23e43977145",
        "fromColumn": "UniqueKey",
        "fromTable": "MetricsByItemandOperation",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "e818060b-43e5-5560-0fc3-ac9d098c915e",
        "fromColumn": "UniqueKey",
        "fromTable": "Performance2daySnapshot",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "33fa74cd-9ff2-b0cc-4d7e-3bfd45ecbf3c",
        "fromColumn": "UniqueKey",
        "fromTable": "MetricsByItemandHour",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "18f8fcbc-5a9c-a388-142d-0f4b2f8f51d5",
        "fromColumn": "UniqueKey",
        "fromTable": "MetricsByItem",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "84fdec63-4b5b-44f2-aa0a-ae2af4d06089",
        "fromColumn": "UniqueKey",
        "fromTable": "MetricsByItemandOperationandDay",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "8d75d48c-0654-46c4-8db8-1a9a5a1e5d7e",
        "fromColumn": "UniqueKey",
        "fromTable": "MetricsByItemandOperationandHour",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "f9ede556-bfb0-4772-b40e-170f67ea0745",
        "fromColumn": "UniqueKey",
        "fromTable": "TimePoint2BackgroundDetail",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "748e736d-ab50-4187-9163-9a82f17a0066",
        "fromColumn": "UniqueKey",
        "fromTable": "MetricsByItemandDay",
        "toColumn": "UniqueKey",
        "toTable": "Items"
      },
      {
        "name": "8758ec7c-c577-4e66-875b-82dd844952b3",
        "fromColumn": "BinnedCapacityStateTransitionTime",
        "fromTable": "SystemEvents",
        "toColumn": "TimePoint",
        "toTable": "TimePoints2"
      },
      {
        "name": "86675b1d-e1b1-4558-912d-4fbd279569a3",
        "fromColumn": "ItemKey",
        "fromTable": "MaxMemoryByItemAndHour",
        "toCardinality": "many",
        "toColumn": "ItemKey",
        "toTable": "Items"
      },
      {
        "name": "68ae4b56-e6d3-8e6b-8314-10b60acc5c10",
        "fromColumn": "ItemKey",
        "fromTable": "MaxMemoryByItem",
        "toCardinality": "many",
        "toColumn": "ItemKey",
        "toTable": "Items"
      },
      {
        "name": "7c3eb136-b8cc-4edb-93b9-ac5133aa0de2",
        "fromColumn": "Start of Hour",
        "fromTable": "TimePoints",
        "toColumn": "Hour Start",
        "toTable": "DateTime"
      },
      {
        "name": "e90a70fb-ae5b-46bd-a72c-3963adacb556",
        "fromColumn": "Timestamp",
        "fromTable": "MaxMemoryByItemAndHour",
        "toColumn": "Hour Start",
        "toTable": "DateTime"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "TimePoints2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TimePoint",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 1,
                  "selectAllValue": "",
                  "version": 2
                }
              }
            ],
            "formatString": "General Date",
            "lineageTag": "36567577-2a39-498f-b08d-5eb3b5115462",
            "sourceColumn": "TimePoint",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "52ca72ca-1400-4dac-a660-c3f823853125",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e3ed9b36-542b-49f8-865e-b03c39e75843",
            "sourceColumn": "Start of Hour",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bab675a0-3aae-46d6-88de-09eed4ef0e42",
        "measures": [
          {
            "name": "End Time 2",
            "expression": "MAX(TimePoints2[TimePoint]) + TIME(0,0,30)",
            "formatString": "General Date",
            "lineageTag": "dd8f8b4e-ed2d-4996-92c6-dd58d6754df0"
          }
        ],
        "partitions": [
          {
            "name": "TimePoints2-55d168ea-0520-47c5-b10f-1e522efccb59",
            "mode": "import",
            "queryGroup": "Direct Query\\TimePoint2",
            "source": {
              "expression": [
                "let",
                "    d = Date.AddDays((DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) + #duration(0,0,0,Number.FromText(UTC_offset)*3600)),-13) ,",
                "    d1 = #datetime(Date.Year(d),Date.Month(d),Date.Day(d),0,0,0),",
                "    Source = List.DateTimes(d1, 20* 24* 60*4 , #duration(0, 0, 0, 30)),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"TimePoint\"}}),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Renamed Columns\", \"Date\", each DateTime.Date([TimePoint]), type date),",
                "    #\"Inserted Start of Hour\" = Table.AddColumn(#\"Inserted Date\", \"Start of Hour\", each Time.StartOfHour([TimePoint]), type datetime),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Inserted Start of Hour\",{{\"TimePoint\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePoints",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TimePoint",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 1,
                  "selectAllValue": "",
                  "version": 2
                }
              }
            ],
            "formatString": "General Date",
            "lineageTag": "ddb4b6d4-2f19-4963-9576-b8d79e7bc4c1",
            "sourceColumn": "TimePoint",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "13e45976-ec44-4455-9f5a-bdb838c77c91",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "974f8545-3d32-47f8-85e6-e4f728e24b2b",
            "sourceColumn": "Start of Hour",
            "summarizeBy": "none"
          },
          {
            "name": "Next",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "444b03c6-c739-4e74-8c57-027bf1831b36",
            "sourceColumn": "Next",
            "summarizeBy": "none"
          },
          {
            "name": "Previous",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5afa3ebb-74a4-4e67-9220-84fc7ba463e2",
            "sourceColumn": "Previous",
            "summarizeBy": "none"
          },
          {
            "name": "15 Minute Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84e0eaa5-2cf4-4b52-b743-ab28349f5881",
            "sourceColumn": "15 Minute Bucket",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "21986ada-dd61-4482-8401-d01917ece215",
        "measures": [
          {
            "name": "Filter 60m",
            "expression": [
              "",
              "VAR OtherSlicerTimePoint = SELECTEDVALUE('timepoints'[timepoint])",
              "VAR ThisSlicerTimePoint = SELECTEDVALUE('TimePoints2'[TimePoint])",
              "RETURN ",
              "IF(ABS(DATEDIFF(ThisSlicerTimePoint,OtherSlicerTimePoint,MINUTE)) <= 30 , 1)"
            ],
            "formatString": "0",
            "lineageTag": "da41540d-3b54-44d0-bfe8-8f6f354cfd6a"
          },
          {
            "name": "End Time",
            "expression": "MAX(TimePoints[TimePoint]) + TIME(0,0,30)",
            "formatString": "General Date",
            "lineageTag": "c802025a-acce-4dcf-a353-a977080b939d"
          }
        ],
        "partitions": [
          {
            "name": "TimePoints-a40a1b49-d0a9-43fa-bab6-78866941aa6a",
            "mode": "import",
            "queryGroup": "Direct Query\\Timepoint",
            "source": {
              "expression": [
                "let",
                "    d = Date.AddDays((DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) + #duration(0,0,0,Number.FromText(UTC_offset)*3600)),-13) ,",
                "    d1 = #datetime(Date.Year(d),Date.Month(d),Date.Day(d),0,0,0),",
                "    Source = List.DateTimes(d1, 20* 24* 60*4 , #duration(0, 0, 0, 30)),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"TimePoint\"}}),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Renamed Columns\", \"Date\", each DateTime.Date([TimePoint]), type date),",
                "    #\"Inserted Start of Hour\" = Table.AddColumn(#\"Inserted Date\", \"Start of Hour\", each Time.StartOfHour([TimePoint]), type datetime),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Inserted Start of Hour\", \"Next\", each \"Next\"),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Previous\", each \"Previous\"),",
                "    #\"Inserted Start of Hour1\" = Table.AddColumn(#\"Added Custom1\", \"15 Minute Bucket\", each [TimePoint] + #duration(0,0,15- Number.Mod(Time.Minute([TimePoint]),15),0-Time.Second([TimePoint])))",
                "in",
                "    #\"Inserted Start of Hour1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePointCUDetail",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "WindowStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9406a389-5b14-4dd3-85ae-fc29ff64f40c",
            "sourceColumn": "WindowStartTime",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "Interactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"\"\\ #,0.###############;#,0.###############\\ -\"\";\"\"\\ #,0.###############",
            "isNullable": false,
            "lineageTag": "eb879fab-4c0a-47e9-bb40-cd737f273670",
            "sourceColumn": "Interactive",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "Background",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"\"\\ #,0.###############;#,0.###############\\ -\"\";\"\"\\ #,0.###############",
            "isNullable": false,
            "lineageTag": "b356ba3e-2aca-4152-8ec3-7115178d548b",
            "sourceColumn": "Background",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "InteractivePreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "eb5c6166-02bc-43a7-84f1-a565939aab8c",
            "sourceColumn": "InteractivePreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "BackgroundPreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "1bdf373d-e9bf-48d1-9347-fd0f6a471d14",
            "sourceColumn": "BackgroundPreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "CUs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.00",
            "isNullable": false,
            "lineageTag": "7f7cadbc-53cd-4e59-9330-e1f6d23c1326",
            "sourceColumn": "CUs",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "WindowEndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ece3b768-176b-43f3-9fc2-ad8925b439f2",
            "sourceColumn": "WindowEndTime",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "StartOfHour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "10cd6e11-3464-4ced-a41d-03c3fefa4053",
            "sourceColumn": "StartOfHour",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "AutoScaleCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "daadfb77-0286-444e-b284-e434b0db0900",
            "sourceColumn": "AutoScaleCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "CU Limit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3cb74804-298c-4a23-ac1c-14d8f889f0cb",
            "sourceColumn": "CU Limit",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Interactive Delay %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a31a369e-d43c-4b40-ba17-7ef048cb4503",
            "sourceColumn": "Interactive Delay %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Interactive Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fb221998-7c80-48ac-81cb-fc890319fbd9",
            "sourceColumn": "Interactive Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Background Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c578c10-6718-47e9-baa2-c1c872275e60",
            "sourceColumn": "Background Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03361016-0f05-4a8b-ad89-28adbac351d3",
            "sourceColumn": "BaseCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHourInteractive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e035ee5d-726c-4fca-99ef-80056cb963a2",
            "sourceColumn": "PeakHourInteractive",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHourBackground",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ac0e42ea-daa6-403d-bf0a-63d556dae583",
            "sourceColumn": "PeakHourBackground",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHourInteractivePreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bcb1cdf4-b6a5-4a3b-a6f0-de256974a35b",
            "sourceColumn": "PeakHourInteractivePreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHourBackgroundPreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d3707545-4661-4a4f-8552-d5eaecc328c9",
            "sourceColumn": "PeakHourBackgroundPreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHour Interactive Delay %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "673cb0b7-5af4-4393-a0a4-c25534993710",
            "sourceColumn": "PeakHour Interactive Delay %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHour Interactive Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b4a2b914-ea32-4804-8418-fd290ea476f8",
            "sourceColumn": "PeakHour Interactive Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHour Background Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "73bdda27-8792-4777-a11d-75765faa11f2",
            "sourceColumn": "PeakHour Background Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d0135dcf-4f13-45d5-8c89-454aee69e2ca",
        "partitions": [
          {
            "name": "TimePointCUDetail-8af51fd0-3e20-43f8-aa7c-267220d29442",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Timepoint",
            "source": {
              "expression": [
                "let",
                "",
                "   Source = fnGetData(\"TimePointCUDetailForTridentV3\", null, null, \"14\"),",
                "",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"WindowStartTime\", type datetime}, {\"WindowEndTime\", type datetime}}),",
                "        begintime= TimePoint - #duration(0,0,30,0),",
                "        endtime = TimePoint +  #duration(0,0,30,0),",
                "r = Table.SelectRows(#\"Changed Type1\", each [WindowStartTime] >= begintime and endtime > [WindowEndTime]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(r,{{\"CpuTimeMs\", Currency.Type}, {\"Interactive\", Currency.Type}, {\"Background\", Currency.Type}}),",
                "    #\"Divided Column\" = Table.TransformColumns(#\"Changed Type\", {{\"CpuTimeMs\", each _ / 1000, Currency.Type}}),",
                "    #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"Interactive\", each _ / 1000, Currency.Type}}),",
                "    #\"Divided Column2\" = Table.TransformColumns(#\"Divided Column1\", {{\"Background\", each _ / 1000, Currency.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Divided Column2\",{{\"CpuTimeMs\", \"CUs\"}}),",
                "    #\"Divided Column3\" = Table.TransformColumns(#\"Renamed Columns\", {{\"InteractivePreview\", each _ / 1000, type number}}),",
                "    #\"Divided Column4\" = Table.TransformColumns(#\"Divided Column3\", {{\"BackgroundPreview\", each _ / 1000, type number}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Divided Column4\", \"CU Limit\", each 1),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"CU Limit\", type number}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePointInteractiveDetail",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OperationStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "abd774e4-c882-4c1b-a3f1-1fc05a2d5127",
            "sourceColumn": "OperationStartTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "OperationEndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f56abf5b-8331-4964-8995-ad79815d04d4",
            "sourceColumn": "OperationEndTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "063483b0-6ba7-4dad-9fc6-ee906dc814e8",
            "sourceColumn": "Status",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc02f25e-8235-413f-9199-f7bad11798dd",
            "sourceColumn": "Item",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "915182da-d1cc-4bc4-9f75-f519d2ce383c",
            "sourceColumn": "Operation",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "OperationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af3661cc-472c-4f0c-b3e4-722556c55b54",
            "sourceColumn": "OperationId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6904059-1f83-44f8-9fb4-8d5368933b90",
            "sourceColumn": "User",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "963f488a-6b4e-4f13-967b-8cfefdf3db3e",
            "sourceColumn": "Start",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "End",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "13fb89e6-6d33-4c78-9276-95033d11f7a0",
            "sourceColumn": "End",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Duration (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "1801608a-f124-41bd-8b92-3f9f4184f0cd",
            "sourceColumn": "Duration (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Throttling (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2172871b-bced-45f7-abab-37a90f48edb2",
            "sourceColumn": "Throttling (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "% of Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "80f5a8bf-d831-4b1a-ad09-8151f7c2f77d",
            "sourceColumn": "% of Capacity",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Total CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.0000",
            "lineageTag": "576794bc-d8f2-4fc3-8cd6-c8c6315ac5bb",
            "sourceColumn": "Total CU (s)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Timepoint CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0000",
            "lineageTag": "c9d92633-18f2-40f4-bf89-6a82b7e8bea4",
            "sourceColumn": "Timepoint CU (s)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Capacity CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d47cb87-e095-431f-a431-e4f01bc8409c",
            "sourceColumn": "Capacity CU (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Base Capacity CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e4be6510-affe-43d4-9a9d-af55d9d8b576",
            "sourceColumn": "Base Capacity CU (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "% of Base Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6fd97a86-513d-480a-9951-81abcac2110b",
            "sourceColumn": "% of Base Capacity",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Billing type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc1340e5-c1fc-4c2c-b09d-cf8a38a12db7",
            "sourceColumn": "Billing type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CapacityActivationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "421d18fd-a520-4e2a-a8b1-97628be99bc6",
            "sourceColumn": "CapacityActivationId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "837882a3-e819-4655-9030-272e5ed89ce6",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e45fb178-6021-40f7-9304-317052cd85f9",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0f166f78-c286-4b89-bb61-809783d1d71f",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "06e309bf-40e4-4b9c-86d5-7c9e4a745ea4",
        "partitions": [
          {
            "name": "TimePointInteractiveDetail-ff0fd930-f4b5-42c4-913e-cf77450d27c0",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Timepoint",
            "source": {
              "expression": [
                "let",
                "  Source = fnGetData(\"TimePointInteractiveDetailForTridentV4\", null, TimePoint, \"14\"),",
                "    Custom1 = Table.RenameColumns(Source,{{\"Artifact\", \"Item\"}})",
                "in",
                "    Custom1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePointBackgroundDetail",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "OperationStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ffb21f83-0359-4c6a-951f-74f24428bd5a",
            "sourceColumn": "OperationStartTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "OperationEndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a4d73c8f-7c1f-471a-8276-472d42bb13e2",
            "sourceColumn": "OperationEndTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "feb3997b-130b-4d72-85bc-0f94f51e459d",
            "sourceColumn": "Status",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d859a5a-c719-45f7-a912-189a9464db15",
            "sourceColumn": "Item",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3537a3b-ceae-42e0-ade4-a09c5806fe9b",
            "sourceColumn": "Operation",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "OperationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc8aed50-c19e-4d05-b6bb-997f45a0f2f1",
            "sourceColumn": "OperationId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e0065c1-5e52-4c7a-968f-f80320e4d780",
            "sourceColumn": "User",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e9ad28ca-3cda-43a0-aef0-35c3450926a4",
            "sourceColumn": "Start",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "End",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f0375b26-ccaf-4983-9be1-81150b28af4d",
            "sourceColumn": "End",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Duration (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "bcd319ec-0c9b-420b-8b35-0880038509a4",
            "sourceColumn": "Duration (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Throttling (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "190dcf26-ed54-49b2-adf6-558a1843448e",
            "sourceColumn": "Throttling (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "% of Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ade29f49-3566-4ee9-875d-d17b190a6544",
            "sourceColumn": "% of Capacity",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Total CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.0000",
            "lineageTag": "6b85bf9e-8dcb-4ec9-ba46-62238a311283",
            "sourceColumn": "Total CU (s)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Timepoint CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.0000",
            "lineageTag": "ebf2db9b-35cd-489e-841f-bcfd98f3913d",
            "sourceColumn": "Timepoint CU (s)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Capacity CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "25288f3d-e557-4c3a-beed-10e206b807b2",
            "sourceColumn": "Capacity CU (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Base Capacity CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3fa24bc4-8e4f-4931-8d4b-adea8f661ae9",
            "sourceColumn": "Base Capacity CU (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "% of Base Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a608c377-71e7-49cc-8d2e-8973f50ef24f",
            "sourceColumn": "% of Base Capacity",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Billing type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0aab063-f943-4832-abb7-0d1ad8d2b93d",
            "sourceColumn": "Billing type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CapacityActivationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05f30214-2984-468c-be80-0ca97d70f509",
            "sourceColumn": "CapacityActivationId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57db963a-0a7a-4f60-a373-c5aacd15da9e",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7759b59-2a3f-499c-915c-b6a930d9ad42",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "36093898-4f94-4b3a-a0d2-69f23e80268f",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "341987e1-faf4-4c73-b7ce-c8536eaaef3b",
        "partitions": [
          {
            "name": "TimePointBackgroundDetail-3c65ac2e-70f5-4bd9-b52d-d287eda394d1",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Timepoint",
            "source": {
              "expression": [
                "let",
                "  Source = fnGetData(\"TimePointBackgroundDetailForTridentV3\", null, TimePoint,\"14\"),",
                "#\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Artifact\", \"Item\"}})",
                "in ",
                "#\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Capacities",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "capacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 1,
                  "selectAllValue": "",
                  "version": 2
                }
              }
            ],
            "isKey": true,
            "lineageTag": "70d8bb7c-bf55-48d0-82e1-4b46f6ea7477",
            "sourceColumn": "capacityId",
            "summarizeBy": "none"
          },
          {
            "name": "state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f390616e-dc17-4816-9853-7de5471afc9d",
            "sourceColumn": "state",
            "summarizeBy": "sum"
          },
          {
            "name": "source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "516f5a59-729a-4187-ae35-80f7bf13a513",
            "sourceColumn": "source",
            "summarizeBy": "sum"
          },
          {
            "name": "capacityPlan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02a2ee0a-926f-4b19-8cbb-505ff8aee695",
            "sourceColumn": "capacityPlan",
            "summarizeBy": "none"
          },
          {
            "name": "capacityNumberOfVCores",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c11a1df-684d-48d6-9c90-08ad424399a9",
            "sourceColumn": "capacityNumberOfVCores",
            "summarizeBy": "sum"
          },
          {
            "name": "capacityMemoryInGB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03933f3f-2303-496e-b413-45925b47ee69",
            "sourceColumn": "capacityMemoryInGB",
            "summarizeBy": "sum"
          },
          {
            "name": "o365AddonId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f7dd69e-5f90-45b9-a2d2-ad5ccbe899d9",
            "sourceColumn": "o365AddonId",
            "summarizeBy": "none"
          },
          {
            "name": "mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9fcf88a7-5878-435b-a2bd-520208c65511",
            "sourceColumn": "mode",
            "summarizeBy": "sum"
          },
          {
            "name": "region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5044de4e-9e48-4a49-bb45-b0c6ef2e9889",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "Capacity Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "lineageTag": "98a0e305-5864-47b3-98ae-7317087e5302",
            "sourceColumn": "Capacity Name",
            "summarizeBy": "none"
          },
          {
            "name": "sku",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd3bda45-53e8-4934-9f16-319b955c483e",
            "sourceColumn": "sku",
            "summarizeBy": "none"
          },
          {
            "name": "creationDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "bad1bc63-f737-42a7-8036-055ddf608cd2",
            "sourceColumn": "creationDate",
            "summarizeBy": "none"
          },
          {
            "name": "Owners",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0380b71-f713-4919-b48d-73a554e866fb",
            "sourceColumn": "Owners",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ddc921d8-c4bd-4ade-9768-8d7634702955",
        "partitions": [
          {
            "name": "Capacities-5710012a-a9f7-4455-b906-b48a78c73d59",
            "mode": "import",
            "queryGroup": "Capacity",
            "source": {
              "expression": [
                "let",
                "    Source = try fnGetData(\"GetCapacitiesForTrident\"),",
                "    ValidateNoErros =",
                "        if not (Source[HasError]) then",
                "            Source[Value]",
                "        else if Text.Contains(Source[Error][Message], \"The column 'Column1' of the table wasn't found.\") then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            error Source[Error][Message],",
                "    SourceWithNull =",
                "        if List.IsEmpty(ValidateNoErros[capacityId]) then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            ValidateNoErros,",
                "                                                                               ",
                "    #\"reorderedColumns2\" = Table.ReorderColumns(",
                "        SourceWithNull,",
                "        {",
                "            \"capacityId\",",
                "            \"state\",",
                "            \"source\",",
                "            \"capacityPlan\",",
                "            \"capacityNumberOfVCores\",",
                "            \"capacityMemoryInGB\",",
                "            \"o365AddonId\",",
                "            \"region\",",
                "            \"displayName\",",
                "            \"sku\",",
                "            \"creationDate\",",
                "            \"Owners\"",
                "        }",
                "    ),",
                "    #\"Renamed Columns\" = Table.RenameColumns(reorderedColumns2, {{\"displayName\", \"Capacity Name\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Items",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "capacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22646a78-46a4-4f2c-82ca-c58462ffaf70",
            "sourceColumn": "capacityId",
            "summarizeBy": "none"
          },
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "914afcfd-dfdc-44cf-8a04-41b7e91c9fa0",
            "sourceColumn": "ItemId",
            "summarizeBy": "none"
          },
          {
            "name": "ItemKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16cd314b-bd24-4e9f-840b-24f9e6eb6cb6",
            "sourceColumn": "ItemKind",
            "summarizeBy": "none"
          },
          {
            "name": "ItemName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe1abed3-c109-44a5-a9c1-7f57cce665d5",
            "sourceColumn": "ItemName",
            "summarizeBy": "none"
          },
          {
            "name": "dcount_Identity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "882d6ab5-64a5-4591-b31e-4c5d6ffae48c",
            "sourceColumn": "dcount_Identity",
            "summarizeBy": "none"
          },
          {
            "name": "Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "96d77170-3dfb-4c24-be7b-d6b6936997c3",
            "sourceColumn": "Timestamp",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31a8d162-0621-4810-ba22-6536080cc9b5",
            "sourceColumn": "WorkspaceId",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1b1722b-10fc-497d-915d-4543ee65abe4",
            "sourceColumn": "WorkspaceName",
            "summarizeBy": "none"
          },
          {
            "name": "Billable type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00821afb-3a4b-4f4a-89d3-4afe2411cd36",
            "sourceColumn": "Billable type",
            "summarizeBy": "none"
          },
          {
            "name": "IsVirtualArtifactName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08bfdaed-5f4c-43ac-b97e-4c999f93e503",
            "sourceColumn": "IsVirtualArtifactName",
            "summarizeBy": "none"
          },
          {
            "name": "IsVirtualWorkspaceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd39ceab-8ea8-4671-9e96-19d38537faa7",
            "sourceColumn": "IsVirtualWorkspaceName",
            "summarizeBy": "none"
          },
          {
            "name": "IsVirtualArtifactStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8b73e54-3ef9-4b3f-8147-366918ea92c6",
            "sourceColumn": "IsVirtualArtifactStatus",
            "summarizeBy": "none"
          },
          {
            "name": "IsVirtualWorkspaceStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e093a1b-731a-416d-8f60-5b110861bb18",
            "sourceColumn": "IsVirtualWorkspaceStatus",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "52d34618-6a98-4a82-b3f2-a89d9d5ed9c4",
            "sourceColumn": "UniqueKey",
            "summarizeBy": "none"
          },
          {
            "name": "ItemKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0404f8dc-b686-454e-8b2b-e3f979a594a9",
            "sourceColumn": "ItemKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7317169a-1593-419e-a03d-bf60db9f0ce2",
        "partitions": [
          {
            "name": "Items-72cc8e2a-9e77-4fa5-b3b5-67608d0fed9c",
            "mode": "import",
            "queryGroup": "Capacity",
            "source": {
              "expression": [
                "let ",
                "   Source = try fnGetData(\"GetCapacitiesForTrident\"),",
                "    ValidateNoErros =",
                "        if not (Source[HasError]) then",
                "            Source[Value]",
                "        else if Text.Contains(Source[Error][Message], \"The column 'Column1' of the table wasn't found.\") then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            error Source[Error][Message],",
                "    SourceWithNull =",
                "        if List.IsEmpty(ValidateNoErros[capacityId]) then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            ValidateNoErros,",
                "   ",
                "#\"Removed Other Columns\" = Table.SelectColumns(SourceWithNull,{\"capacityId\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Other Columns\", \"myCustomFunction\",  each fnGetData(\"ArtifactsV4ForTrident\",[capacityId])),    ",
                "#\"Expanded myCustomFunction\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"myCustomFunction\", {\"ArtifactId\", \"ArtifactKind\", \"ArtifactName\", \"dcount_Identity\", \"Timestamp\", \"WorkspaceId\", \"WorkspaceName\",\"ReleaseType\", \"IsVirtualArtifactName\",\"IsVirtualWorkspaceName\",\"UniqueKey\"}, {\"ArtifactId\", \"ArtifactKind\", \"ArtifactName\", \"dcount_Identity\", \"Timestamp\", \"WorkspaceId\", \"WorkspaceName\",\"ReleaseType\",\"IsVirtualArtifactStatus\",\"IsVirtualWorkspaceStatus\",\"UniqueKey\"}), ",
                "#\"Uppercased Text\" = Table.TransformColumns(#\"Expanded myCustomFunction\",{{\"ArtifactId\", Text.Upper, type text}}),     ",
                "#\"Filtered Rows\" = Table.SelectRows(#\"Uppercased Text\", each [ArtifactId] <> null and [ArtifactId] <> \"\"),   ",
                "#\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",each [ReleaseType],",
                "          each if [ReleaseType] = \"Preview\" then \"Non-billable\" else \"Billable\",",
                "          Replacer.ReplaceValue,{\"ReleaseType\"}),",
                "#\"Renamed Columns1\" = Table.RenameColumns(#\"Replaced Value\",{{\"ReleaseType\", \"Billable type\"}}),",
                "#\"Sorted Rows\" = Table.Sort(#\"Renamed Columns1\",{\"Timestamp\", Order.Descending}),    ",
                "#\"Buffer\" = Table.Buffer(#\"Sorted Rows\"),",
                "#\"Removed Duplicates\" = Table.Distinct(#\"Buffer\", {\"UniqueKey\"}),",
                "#\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"ArtifactId\", \"ItemId\"}, {\"ArtifactKind\", \"ItemKind\"}, {\"ArtifactName\", \"ItemName\"}}),",
                "#\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"Timestamp\", type datetime}}),",
                "#\"Added Custom2\" = Table.AddColumn(#\"Changed Type\", \"IsVirtualArtifactName\", each if [IsVirtualArtifactStatus] then \"True\" else \"False\"),",
                "#\"Added Custom3\" = Table.AddColumn(#\"Added Custom2\", \"IsVirtualWorkspaceName\", each if [IsVirtualWorkspaceStatus] then \"True\" else \"False\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Custom3\",{\"UniqueKey\", \"capacityId\", \"ItemId\", \"ItemKind\", \"ItemName\", \"dcount_Identity\", \"Timestamp\", \"WorkspaceId\", \"WorkspaceName\", \"Billable type\", \"IsVirtualArtifactStatus\", \"IsVirtualWorkspaceStatus\", \"IsVirtualArtifactName\", \"IsVirtualWorkspaceName\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Reordered Columns\", \"ItemKey\", each [capacityId]&[ItemId])",
                "in   ",
                "#\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "All Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "284cf299-bd71-4fb7-bb78-413a2447a0ea",
        "measures": [
          {
            "name": "Count of Background Operations Preview",
            "expression": "COUNTROWS('TimePointBackgroundDetail')",
            "formatString": "0",
            "lineageTag": "8f3e480e-64c6-474d-9f72-32b8c3eb939b"
          },
          {
            "name": "Count of Interactive Operations Preview",
            "expression": "COUNTROWS('TimePointInteractiveDetail')",
            "formatString": "0",
            "lineageTag": "2633eb43-e467-4b82-b271-33e520e88504"
          },
          {
            "name": "SKU CU by TimePoint short % Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "\tVAR TimePoint = SELECTEDVALUE('TimePointCUDetail'[WindowStartTime])",
              "\tVAR CU = ",
              "\t\tVAR BaseCoreCount = MAX('TimePointCUDetail'[BaseCapacityUnits]) * 30",
              "\t\tVAR AutoScaleCoreCount = MAX('TimePointCUDetail'[AutoScaleCapacityUnits])",
              "\t\tVAR ResultASSeconds = BaseCoreCount + IF(AutoScaleCoreCount>0,AutoScaleCoreCount*30)",
              "\t\tRETURN DIVIDE(ResultASSeconds,BaseCoreCount)",
              "",
              "\tRETURN CU ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "927407b8-a274-4569-ba3c-53e746a999b5"
          },
          {
            "name": "SKU CU by TimePoint short Preview",
            "expression": [
              "",
              "\tVAR TimePoint = SELECTEDVALUE('TimePointCUDetail'[WindowEndTime])",
              "\tVAR CU = ",
              "\t\tVAR BaseCoreCount = MAX('TimePointCUDetail'[BaseCapacityUnits]) ",
              "\t\tVAR AutoScaleCoreCount = MAX(TimePointCUDetail[AutoScaleCapacityUnits])",
              "\t\tRETURN (BaseCoreCount * 30) ",
              "\tRETURN CU "
            ],
            "formatString": "0",
            "lineageTag": "3620a102-529a-44cc-b3ba-828a08cb163f"
          },
          {
            "name": "Sum of Timepoint Detail CU % Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    VAR nominator = MAX('TimePointCUDetail'[Interactive]) + MAX('TimePointCUDetail'[Background]) +  MAX('TimePointCUDetail'[InteractivePreview]) + MAX('TimePointCUDetail'[BackgroundPreview])",
              "    VAR denominator = [SKU CU by TimePoint short Preview]",
              "    RETURN divide(nominator,denominator)"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "926f3610-cf6b-499c-803a-3145edd0d31a"
          },
          {
            "name": "Cumulative CU Usage % Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[xInteractive %] + [xInteractive % Preview] + [xBackground %] + [xBackground % Preview]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "76c1f206-e436-4b3c-8d77-52feb69b6383"
          },
          {
            "name": "Dynamic M1 CU Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        //VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "        RETURN ",
              "            SWITCH (",
              "                TRUE (),",
              "                not isFiltered_Hour && not isFiltered_Op && not isFiltered_Day,SUM ( \t\t'MetricsByItem'[sum_CU] ),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day,SUM ( \t\t'MetricsByItemandDay'[sum_CU] )  ,",
              "                isFiltered_Op && not isFiltered_Day,SUM ( \t\t'MetricsByItemandOperation'[sum_CU] ),",
              "                not isFiltered_Hour &&  isFiltered_Op,SUM ( \t\t'MetricsByItemandOperationandDay'[sum_CU] ),",
              "                SUM ( 'MetricsByItemandOperationandHour'[sum_CU] )               ",
              "",
              "                )",
              ""
            ],
            "formatString": "#,0.0000",
            "lineageTag": "72fc696e-f7df-4baf-8563-21702e18209b"
          },
          {
            "name": "Dynamic M1 Duration Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        //VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "        RETURN ",
              "            SWITCH (",
              "                TRUE (),",
              "                not isFiltered_Hour && not isFiltered_Op && not isFiltered_Day,SUM ('MetricsByItem'[sum_duration] ),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day,SUM ( \t\t'MetricsByItemandDay'[sum_duration] )  ,",
              "                isFiltered_Op && not isFiltered_Day,SUM ( \t\t'MetricsByItemandOperation'[sum_duration] ),",
              "                not isFiltered_Hour &&  isFiltered_Op,SUM ( \t\t'MetricsByItemandOperationandDay'[sum_duration] ),",
              "                SUM ( 'MetricsByItemandOperationandHour'[sum_duration] )               ",
              "                ) ",
              "",
              ""
            ],
            "formatString": "#,0.0000",
            "lineageTag": "4156b12c-d2ba-4cfc-81b3-104bd6777d80"
          },
          {
            "name": "Dynamic M1 Memory Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "VAR isOnArtifactLevel = IF( COUNT('OperationNames'[OperationName]) > 0, TRUE(), FALSE())",
              "VAR myArtifactKind = SELECTEDVALUE('Items'[ItemKind],\"\")",
              "VAR isFiltered_Day = ISFILTERED(Dates[Date])",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        myArtifactKind <> \"Dataset\" && myOperationName=\"\" , blank(), ",
              "        myOperationName=\"\" && isOnArtifactLevel && isFiltered_Day, MAX(MaxMemoryByItemAndHour[Item Size (GB)]),",
              "        myOperationName=\"\" && isOnArtifactLevel, MAX(MaxMemoryByItem[Item Size (GB)])",
              "        )"
            ],
            "formatString": "0.0000",
            "lineageTag": "51f1fd8c-7a75-412a-9067-68c98da8a8e6"
          },
          {
            "name": "Dynamic M1 Perf Preview",
            "expression": [
              "",
              "VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "VAR isOnOperationLevel = IF( COUNT('OperationNames'[OperationName]) > 0, TRUE(), FALSE())",
              "VAR isOnArtifactLevel = IF( COUNT(Items[ItemId]) > 1, TRUE(), FALSE()) ",
              "VAR myArtifactKind = SELECTEDVALUE('Items'[ItemKind],\"\")",
              "",
              "RETURN ",
              "",
              "    SWITCH(",
              "        TRUE(),",
              "        isOnArtifactLevel, blank(),",
              "        myArtifactKind <> \"Dataset\" && myOperationName=\"\" , blank() ,",
              "        myOperationName=\"\" && isOnOperationLevel ,  IFERROR(MAX(Performance2daySnapshot[Performance delta]),blank())",
              "        )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "46780fe2-73ce-48bb-91bf-49c1b9e05dc8"
          },
          {
            "name": "Dynamic M1 Users Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "        RETURN ",
              "",
              "",
              "            SWITCH (",
              "                TRUE (),",
              "                not isFiltered_Hour && not isFiltered_Op && not isFiltered_Day,               MAX( \t\t'MetricsByItem'[count_users] ), ",
              "                not isFiltered_Hour &&    isFiltered_Op && not isFiltered_Day ,                MAX ( 'MetricsByItemandOperation'[count_users] ),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day, MAX ( 'MetricsByItemandDay'[count_users] )  ,",
              "                not isFiltered_Hour && not isFiltered_Op,                   MAX ( 'MetricsByItemandDay'[count_users] ),",
              "                isFiltered_Op && not isFiltered_Day ,                        MAX ( 'MetricsByItemandOperation'[count_users] ),",
              "                not isFiltered_Hour &&  isFiltered_Op,                      MAX ( 'MetricsByItemandOperationandDay'[count_users] ),",
              "                MAX ( 'MetricsByItemandOperationandHour'[count_users] )               ",
              "",
              "                )"
            ],
            "formatString": "#,0",
            "lineageTag": "e5e14288-d69e-4686-80a9-f0d77b36658a"
          },
          {
            "name": "Dynamic Metric Item 1 Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "",
              "        VAR DynamicCalc =  (",
              "            SWITCH (",
              "                TRUE (),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day,",
              "                    SWITCH (",
              "                        SELECTEDVALUE ( 'Metrics'[Metric] ),",
              "                        \"Duration\", SUM ( \t'MetricsByItemandDay'[sum_duration] ),",
              "                        \"CU\", SUM ( \t\t'MetricsByItemandDay'[sum_CU] ),",
              "                        \"Operations\", SUM ( 'MetricsByItemandDay'[count_operations] ),",
              "                        \"Users\", MAX ( \t\t'MetricsByItemandDay'[count_users] ) ",
              "",
              "                    ),",
              "",
              "                not isFiltered_Hour && not isFiltered_Op,",
              "                    SWITCH (",
              "                        SELECTEDVALUE ( 'Metrics'[Metric] ),",
              "                        \"Duration\", SUM ( \t'MetricsByItemandDay'[sum_duration] ),",
              "                        \"CU\", SUM ( \t\t'MetricsByItemandDay'[sum_CU] ),",
              "                        \"Operations\", SUM ( 'MetricsByItemandDay'[count_operations] ),",
              "                       ",
              "                        \"Users\", MAX ( \t\t'MetricsByItem'[count_users] ) ",
              "                       ),",
              "                isFiltered_Op && not isFiltered_Day,",
              "",
              "                    SWITCH (",
              "                        SELECTEDVALUE ( 'Metrics'[Metric] ),",
              "                        \"Duration\", SUM ( \t'MetricsByItemandOperation'[sum_duration] ),",
              "                        \"CU\", SUM ( \t\t'MetricsByItemandOperation'[sum_CU] ),",
              "                        \"Operations\", SUM ( 'MetricsByItemandOperation'[count_operations] ),",
              "                        \"Users\", MAX ( \t\t'MetricsByItemandOperation'[count_users] )",
              "                    ),",
              "                not isFiltered_Hour &&  isFiltered_Op,",
              "                    SWITCH (",
              "                        SELECTEDVALUE ( 'Metrics'[Metric] ),",
              "                        \"Duration\", SUM ( \t'MetricsByItemandOperationandDay'[sum_duration] ),",
              "                        \"CU\", SUM ( \t\t'MetricsByItemandOperationandDay'[sum_CU] ),",
              "                        \"Operations\", SUM ( 'MetricsByItemandOperationandDay'[count_operations] ),",
              "                        \"Users\", MAX ( \t\t'MetricsByItemandOperationandDay'[count_users] )",
              "                       )",
              "                    ,                ",
              "                    isFiltered_Hour && not isFiltered_Op ,",
              "                    SWITCH (",
              "                        SELECTEDVALUE ( 'Metrics'[Metric] ),",
              "                        \"Duration\", SUM (   'MetricsByItemandHour'[sum_duration] ),",
              "                        \"CU\", SUM (        'MetricsByItemandHour'[sum_CU] ),",
              "                        \"Operations\", SUM ( 'MetricsByItemandHour'[count_operations] ),",
              "                        \"Users\",  MAX (         'MetricsByItemandHour'[count_users] )",
              "                       )",
              "                    ,              ",
              "",
              "",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Metrics'[Metric] ),",
              "                    \"Duration\", SUM ( 'MetricsByItemandOperationandHour'[sum_duration] ),",
              "                    \"CU\", SUM ( 'MetricsByItemandOperationandHour'[sum_CU] ),",
              "                    \"Operations\", SUM ( 'MetricsByItemandOperationandHour'[count_operations] ),",
              "                    \"Users\", MAX ( 'MetricsByItemandOperationandHour'[count_users] )",
              "                        )",
              "",
              "            ))",
              "",
              "    RETURN ",
              "        SWITCH( ",
              "            TRUE(), ",
              "            myMetric in {\"Perf 1\",\"Perf 2\"} && myOperationName<>\"\" , blank(),",
              "          ",
              "            myMetric in {\"Perf 1\",\"Perf 2\"}&& hasOneFilter_Day , blank(),",
              "",
              "            DynamicCalc)"
            ],
            "formatString": "0.0000",
            "lineageTag": "9bcdeb28-8ecf-4453-81c1-c01dbb094918"
          },
          {
            "name": "Dynamic Text for Matrix Title",
            "expression": [
              "",
              "VAR isFiltered_Day = ISFILTERED(Dates[Date])",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        isFiltered_Day, \"Items (\" & COUNTROWS(VALUES('DateTime'[Date])) & \" days)\",",
              "        \"Items (14 days)\"",
              "    )"
            ],
            "lineageTag": "857ccbbb-d410-423e-af73-1beed4ff12b4"
          },
          {
            "name": "Metric description Preview",
            "expression": [
              "",
              "VAR selectedMetric = SELECTEDVALUE('Metrics'[Metric],\"\")",
              "RETURN ",
              "    SWITCH",
              "        (",
              "            selectedMetric ,",
              "\t\t\t\"CU\" , \"CU shows Capacity Units processing time in seconds including fabric workloads.\" ,",
              "            \"Duration\" , \"The actual time taken to complete the operation including fabric workloads.\" ,",
              "            \"Operations\" , \"The count of individual operations that took place including fabric workloads.\" ,",
              "            \"Users\" , \"The distinct number of users who performed the operation including fabric workloads.\" ,",
              "            \"This is a test\"",
              "            )"
            ],
            "lineageTag": "6f15cc6c-6dc9-448c-98fb-239c790b49d3"
          },
          {
            "name": "SKU CU by TimePoint",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR x = [xInteractive]",
              "var y = [xBackground]",
              "VAR a = [xBackgroundPreview]",
              "VAR b = [xInteractivePreview]",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('CUDetail'[BaseCapacityUnits]) ",
              "    VAR AutoScaleCoreCount = MAX(CUDetail[AutoScaleCapacityUnits])",
              "    RETURN (BaseCoreCount * 30) + IF(AutoScaleCoreCount>0,AutoScaleCoreCount*30)",
              "RETURN if(not isblank(x) || not isblank(y) || not isblank(a) || not isblank(b),CU) "
            ],
            "formatString": "0",
            "lineageTag": "fb95fe80-2178-4d9c-9855-da2e7186ce22"
          },
          {
            "name": "SKU CU by TimePoint %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR denominator = ",
              "    VAR BaseCoreCount = MAX('CUDetail'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30) ",
              "VAR Numerator = 'All Measures'[SKU CU by TimePoint]",
              "RETURN Divide(Numerator, denominator)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9256c3c1-d0a6-4499-b28a-8cda7c750958"
          },
          {
            "name": "SKU CU by TimePoint Basecore Only",
            "expression": [
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR x = [xInteractive]",
              "var y = [xBackground]",
              "VAR a = [xBackgroundPreview]",
              "VAR b = [xInteractivePreview]",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('CUDetail'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30) ",
              "RETURN if(not isblank(x) || not isblank(y) || not isblank(a) || not isblank(b),CU) ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1575235a-bc3a-4790-9f93-8b77a9fd8f1a"
          },
          {
            "name": "SKU CU by TimePoint Basecore Only Preview",
            "expression": [
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR x = [xInteractivePreview]",
              "var y = [xBackgroundPreview]",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('CUDetail'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30)",
              "RETURN if(not isblank(x) || not isblank(y),CU) "
            ],
            "formatString": "0",
            "lineageTag": "da727a9b-fc82-45d0-bbb5-491612e676a5"
          },
          {
            "name": "SKU CU by TimePoint Timepoint Card Preview",
            "expression": [
              "",
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints'[TimePoint])",
              "",
              "VAR CU =",
              "",
              "    VAR BaseCoreCount = MAX('TimePointCUDetail'[BaseCapacityUnits])",
              "",
              "    VAR AutoScaleCoreCount = MAX(TimePointCUDetail[AutoScaleCapacityUnits])",
              "",
              "    RETURN (BaseCoreCount * 30) + IF(AutoScaleCoreCount>0,AutoScaleCoreCount*30)",
              "",
              "RETURN CU"
            ],
            "formatString": "0",
            "lineageTag": "80bb4ef2-cd22-4f26-a953-27546bc4cb15"
          },
          {
            "name": "xBackground %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR Numerator = 'All Measures'[xBackground]",
              "VAR denominator = 'All Measures'[SKU CU by TimePoint Basecore Only]",
              "RETURN DIVIDE(Numerator,denominator)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2c0bd329-0929-4d58-9bee-fb18e66d8b59"
          },
          {
            "name": "xBackground % Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR Numerator = 'All Measures'[xBackgroundPreview]",
              "VAR denominator = 'All Measures'[SKU CU by TimePoint Basecore Only]",
              "RETURN DIVIDE(Numerator,denominator)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b3e2eb12-2719-4629-a228-16bd6b707f6c"
          },
          {
            "name": "xInteractive %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR Numerator = 'All Measures'[xInteractive]",
              "VAR denominator = 'All Measures'[SKU CU by TimePoint Basecore Only]",
              "RETURN DIVIDE(Numerator,denominator)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "71bec6ee-5996-4276-b418-e087cefa2176"
          },
          {
            "name": "xInteractive % Preview",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR Numerator = 'All Measures'[xInteractivePreview]",
              "VAR denominator = 'All Measures'[SKU CU by TimePoint Basecore Only]",
              "RETURN DIVIDE(Numerator,denominator)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fdb93ef1-38db-4063-8ba8-60b07f1d44c4"
          },
          {
            "name": "SKU CU by TimePoint short Preview (2)",
            "expression": [
              "",
              "\tVAR TimePoint = SELECTEDVALUE('TimePoint2CUDetail'[WindowEndTime])",
              "\tVAR CU = ",
              "\t\tVAR BaseCoreCount = MAX('TimePoint2CUDetail'[BaseCapacityUnits]) ",
              "\t\tVAR AutoScaleCoreCount = MAX('TimePoint2CUDetail'[AutoScaleCapacityUnits])",
              "\t\tRETURN (BaseCoreCount * 30)",
              "\tRETURN CU "
            ],
            "formatString": "0",
            "lineageTag": "c72b0a3a-a5b3-4352-b656-98654b3cf41e"
          },
          {
            "name": "SKU CU by TimePoint short % Preview (2)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "\tVAR TimePoint = SELECTEDVALUE('TimePoint2CUDetail'[WindowStartTime])",
              "\tVAR CU = ",
              "\t\tVAR BaseCoreCount = MAX('TimePoint2CUDetail'[BaseCapacityUnits]) * 30",
              "\t\tVAR AutoScaleCoreCount = MAX('TimePoint2CUDetail'[AutoScaleCapacityUnits])",
              "\t\tVAR ResultASSeconds = BaseCoreCount + IF(AutoScaleCoreCount>0,AutoScaleCoreCount*30)",
              "\t\tRETURN DIVIDE(ResultASSeconds,BaseCoreCount)",
              "",
              "\tRETURN CU ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d53b3857-60cf-4980-acab-631322d4edb0"
          },
          {
            "name": "Sum of Timepoint Detail CU % Preview (2)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    VAR nominator = MAX('TimePoint2CUDetail'[Interactive]) + MAX('TimePoint2CUDetail'[Background]) +  MAX('TimePoint2CUDetail'[InteractivePreview]) + MAX('TimePoint2CUDetail'[BackgroundPreview])",
              "    VAR denominator = [SKU CU by TimePoint short Preview (2)]",
              "    RETURN divide(nominator,denominator)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6d20e5cc-78d5-4deb-ad1d-888f5bf7dab4"
          },
          {
            "name": "Count of Interactive Operations Preview 2",
            "expression": "COUNTROWS('TimePoint2InteractiveDetail')",
            "formatString": "0",
            "lineageTag": "79716b51-129a-43b9-83c2-313004990200"
          },
          {
            "name": "Count of Background Operations Preview 2",
            "expression": "COUNTROWS('TimePoint2BackgroundDetail')",
            "formatString": "0",
            "lineageTag": "7ad73b2a-c14e-4bd7-83a6-a5faaf3944bf"
          },
          {
            "name": "CU (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "MAX('TimePointCUDetail'[Interactive]) + MAX('TimePointCUDetail'[Background]) +  MAX('TimePointCUDetail'[InteractivePreview]) + MAX('TimePointCUDetail'[BackgroundPreview])"
            ],
            "lineageTag": "9a2e490c-6197-435c-8ee7-d8f4a673d4c6"
          },
          {
            "name": "CU (s)(2)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " MAX('TimePoint2CUDetail'[Interactive]) + MAX('TimePoint2CUDetail'[Background]) +  MAX('TimePoint2CUDetail'[InteractivePreview]) + MAX('TimePoint2CUDetail'[BackgroundPreview])"
            ],
            "lineageTag": "5a236c6c-fe29-46ee-8d7b-ce95e6c71d76"
          },
          {
            "name": "Cumulative CU Usage (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[xInteractive] + [xInteractivePreview] + [xBackground] + [xBackgroundPreview]",
            "lineageTag": "5a9be63f-26ca-45d7-96d9-28f03040c7b3"
          },
          {
            "name": "CU Limit",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR x = [xInteractive]",
              "var y = [xBackground]",
              "VAR a = [xBackgroundPreview]",
              "VAR b = [xInteractivePreview]",
              "RETURN if(not isblank(x) || not isblank(y) || not isblank(a) || not isblank(b),1)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4dfa2fe0-a5ed-4922-b66f-cbbeb5e6fee5"
          },
          {
            "name": "Dynamic Preview Status",
            "expression": [
              "",
              "// VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "// VAR isOnOperationLevel = IF( COUNT('OperationNames'[OperationName]) > 0, TRUE(), FALSE())",
              "VAR isOnArtifactLevel = IF( COUNT(Items[ItemId]) > 1, TRUE(), FALSE()) ",
              "// VAR myArtifactKind = SELECTEDVALUE('Items'[ItemKind],\"\")",
              "",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        isOnArtifactLevel, blank(),",
              "        MAX(Items[Billable type])",
              "        )"
            ],
            "lineageTag": "981c1df5-2b96-4a14-9f8a-377c78f03908"
          },
          {
            "name": "SKU CU by TimePoint Autoscale only",
            "expression": [
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints'[TimePoint])",
              "",
              "VAR CU = ",
              "    VAR AutoScaleCoreCount = MAX('CUDetail'[AutoScaleCapacityUnits])",
              "    RETURN (IF(AutoScaleCoreCount>0,AutoScaleCoreCount*30,0))",
              "RETURN CU"
            ],
            "formatString": "0",
            "lineageTag": "addcad5e-af25-4972-8b73-0600bf9a3b41"
          },
          {
            "name": "SKU CU by Timepoint Basecore",
            "expression": [
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints'[TimePoint])",
              "",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('CUDetail'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30)",
              "RETURN CU ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a4c9f6be-8658-433b-9bca-56b4e318dec4"
          },
          {
            "name": "Dynamic M1 Utilization (GB)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "        VAR isFiltered_Hour = ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Workspace = ISFILTERED(Workspaces[WorkspaceId])",
              "        VAR isFiltered_Day = ISFILTERED('Dates'[Date])  ",
              "        VAR isFiltered_Day_Month = ISFILTERED('Dates'[Day]) ",
              "        VAR isFiltered_1st_Day_of_Week = ISFILTERED('Dates'[First Day of Week])",
              "",
              "        VAR x =  ",
              "            SWITCH (",
              "                TRUE (),",
              "                 ",
              "                isFiltered_Workspace && not isFiltered_Hour &&  isFiltered_Day,sum(StorageByWorkspacesandDay[Utilization (GB)]),",
              "                not isFiltered_Workspace && not isFiltered_Hour &&  isFiltered_Day,sum(StorageByWorkspacesandDay[Utilization (GB)]),",
              "\t\tisFiltered_Hour ,SUM (StorageByWorkspacesandHour[Utilization (GB)])  ,",
              "                isFiltered_Day_Month || isFiltered_1st_Day_of_Week ,sum(StorageByWorkspacesandDay[Utilization (GB)]),",
              "                SUM(StorageByWorkspacesandDay[Utilization (GB)])              ",
              "                )",
              "",
              "        RETURN x"
            ],
            "lineageTag": "9dd9287d-a81d-4ab7-82b8-07c20d7e7f20"
          },
          {
            "name": "OneLake Rank Workspace Visual",
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "VAR x = SELECTEDVALUE('Top N Selector'[Top N])",
              "",
              "RETURN",
              "IF (",
              "    ISINSCOPE (Workspaces[WorkspaceName]),",
              "    INT (",
              "        RANKX (",
              "            CALCULATETABLE (",
              "                GROUPBY( 'Workspaces','Workspaces'[WorkspaceKey],Workspaces[WorkspaceName], Workspaces[WorkspaceId]),",
              "                ALLSELECTED ( Workspaces )",
              "            ),",
              "            CALCULATE ( [Dynamic M1 Cumulative Utilization (GB) by Workspace] )",
              "        )",
              "            <= MAX ( 'Top N Selector'[Top N]  )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bc0c40cc-443b-4067-ab19-5139af1bb29d"
          },
          {
            "name": "Last Carry Over Burdown",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE ( SUM ( TimePointOveragesByWorkloads[CarryForwardBurndown] ), TimePointOveragesByWorkloads[WindowStartTime] == MAX(TimePoints[TimePoint]))"
            ],
            "lineageTag": "66c55378-bb5e-4009-8018-a81eea907fca"
          },
          {
            "name": "Utilization (GB) % Workspace 1",
            "expression": [
              "",
              "VAR base = [Dynamic M1 Utilization (GB)]",
              "VAR baseparent = CALCULATE(SUM(StorageByWorkspacesandHour[Utilization (GB)]),",
              "        ALL ( 'Workspaces'[WorkspaceId]),",
              "        ALL(Workspaces[WorkspaceName])",
              "     )",
              "  ",
              "VAR Percentage = DIVIDE ( base, baseparent )",
              "",
              " RETURN  IF(ISBLANK(Percentage),0,Percentage)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3f1e2b4c-e1d7-4a2c-8d1c-17b2a4b761db"
          },
          {
            "name": "Dynamic Text for Workspaces Title",
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "VAR x = SELECTEDVALUE('Top N Selector'[Top N])",
              "RETURN \"Top \"&x& \" workspaces by billable storage (GB) %\""
            ],
            "lineageTag": "3a226742-0a35-48dc-805e-e358bd66a2d4"
          },
          {
            "name": "Total Cumulative Storage in GB",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "    sum(StorageByWorkspacesandDay[StaticStorageInGb])"
            ],
            "lineageTag": "4e3e8f41-9e9c-4ca0-a814-e286404b39ee"
          },
          {
            "name": "SKU CU CarryOver",
            "expression": [
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR x = [xCarryOver_added]",
              "VAR y = [xCarryOver_burndown]",
              "VAR z = [Expected burndown in minutes]",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('TimePointOverageDetail'[BaseCapacityUnits]) ",
              "    VAR AutoScaleCoreCount = MAX(TimePointOverageDetail[AutoScaleCapacityUnits])",
              "    RETURN (BaseCoreCount * 30) // + IF(AutoScaleCoreCount>0,AutoScaleCoreCount*30,0)",
              "RETURN if(not isblank(x) || not isblank(y) || not isblank(z),CU)"
            ],
            "formatString": "0",
            "lineageTag": "696f1881-9243-4f5d-8ecf-e18da6ff7d9f"
          },
          {
            "name": "xCarryOver_added",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR y = MAX('TimePointOverageDetail'[CarryForwardAdd])",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('TimePointOverageDetail'[Peak20minCarryForwardAdd])/1000",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )"
            ],
            "lineageTag": "c649dcb4-daff-4463-8e1e-c973c990f0c3"
          },
          {
            "name": "xCarryOver_burndown",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR y = MAX('TimePointOverageDetail'[CarryForwardBurndown])",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('TimePointOverageDetail'[Peak20minCarryForwardBurndown])/1000",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )"
            ],
            "lineageTag": "15ba9789-652b-40a8-bca0-9c04601f6c40"
          },
          {
            "name": "Expected burndown in minutes",
            "expression": "SUM(TimePointOverageDetail[CumulativeCarryForward])/(2*30*SUM(TimePointOverageDetail[BaseCapacityUnits]))",
            "formatString": "0.00",
            "lineageTag": "c240aa8f-0a49-49c7-94a6-1e2c681d03a0"
          },
          {
            "name": "xCarryOver_added %",
            "expression": [
              "",
              "VAR Numerator = [xCarryOver_added]",
              "VAR denominator = 'All Measures'[SKU CU CarryOver]",
              "RETURN DIVIDE(Numerator,denominator)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8a957c99-5eee-4e0a-8b17-77cee6a1df7e"
          },
          {
            "name": "xCarryOver_burndown %",
            "expression": [
              "",
              "VAR Numerator = [xCarryOver_burndown]",
              "VAR denominator = 'All Measures'[SKU CU CarryOver]",
              "RETURN DIVIDE(Numerator,denominator)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "37085625-a7e5-44bc-aa42-edb4e82375bf"
          },
          {
            "name": "xCarryOver_Cumulative %",
            "expression": [
              "",
              "VAR Numerator = [xCarryOver_cumulative]",
              "VAR denominator = 'All Measures'[SKU CU CarryOver]",
              "RETURN DIVIDE(Numerator,denominator)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "beccb2e3-620a-47c2-bc14-7e9d48d5bb3d"
          },
          {
            "name": "Timepoint SKU CU CarryOver",
            "expression": [
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('TimePointOveragesByWorkloads'[BaseCapacityUnits]) ",
              "    VAR AutoScaleCoreCount = MAX(TimePointOveragesByWorkloads[AutoScaleCapacityUnits])",
              "    RETURN (BaseCoreCount * 30) // + IF(AutoScaleCoreCount>0,AutoScaleCoreCount*30,0)",
              "RETURN CU"
            ],
            "formatString": "0",
            "lineageTag": "19fd3636-8b7f-4b62-9d45-9800f7f9e0e4"
          },
          {
            "name": "Last Cumulative Carry Over",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE ( SUM ( TimePointOveragesByWorkloads[CumulativeCarryForward] ), TimePointOveragesByWorkloads[WindowStartTime] == MAX(TimePoints[TimePoint]))"
            ],
            "lineageTag": "0c8585ec-a326-4f23-b6c9-a41b96d924d5"
          },
          {
            "name": "Last Cumulative Carry Over %",
            "expression": "[Last Cumulative Carry Over]/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "603921dd-a2f3-4f9c-b945-0396c58b45db"
          },
          {
            "name": "Last 24 hrs CarryForward Add %",
            "expression": "SUM(TimePointOveragesByWorkloads[CarryForwardAdd])/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "7f16e186-2a56-4145-bcd8-042369f696d8"
          },
          {
            "name": "Last 24 hrs CarryForward Burndown %",
            "expression": "SUM(TimePointOveragesByWorkloads[CarryForwardBurndown])/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "159561c2-98cd-4422-9148-d93a6eb9dbf0"
          },
          {
            "name": "Last 24 hrs Cumulative CarryForward %",
            "expression": "SUM(TimePointOveragesByWorkloads[CumulativeCarryForward])/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "48af8ccc-75ad-4660-8c93-216968d57830"
          },
          {
            "name": "Last 60 Minutes CumulativeCarryForward",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( TimePointOveragesByWorkloads[CumulativeCarryForward] ),",
              "    FILTER (",
              "        TimePointOveragesByWorkloads,",
              "        TimePointOveragesByWorkloads[WindowStartTime] >= MAX(TimePoints[TimePoint]) - TIME(0, 60, 0) ",
              "    )",
              ")"
            ],
            "lineageTag": "e75ed7ff-0b82-42de-b6b1-58a7bd61e940"
          },
          {
            "name": "Last 60 Minutes CumulativeCarryForward %",
            "expression": "[Last 60 Minutes CumulativeCarryForward]/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "1962c148-67ae-4efe-b26f-486aa32e016b"
          },
          {
            "name": "Last 60 Minutes CarryForwardAdd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( TimePointOveragesByWorkloads[CarryForwardAdd] ),",
              "    FILTER (",
              "        TimePointOveragesByWorkloads,",
              "        TimePointOveragesByWorkloads[WindowStartTime] >= MAX(TimePoints[TimePoint]) - TIME(0, 60, 0) ",
              "    )",
              ")"
            ],
            "lineageTag": "6e54576a-dbf8-4f79-bba3-45ed33bdc773"
          },
          {
            "name": "Last 60 Minutes CarryForwardAdd %",
            "expression": "[Last 60 Minutes CarryForwardAdd]/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "74c68228-694e-454a-8f29-1a355b702819"
          },
          {
            "name": "Last 60 Minutes CarryForwardBurndown",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( TimePointOveragesByWorkloads[CarryForwardBurndown] ),",
              "    FILTER (",
              "        TimePointOveragesByWorkloads,",
              "        TimePointOveragesByWorkloads[WindowStartTime] >= MAX(TimePoints[TimePoint]) - TIME(0, 60, 0) ",
              "    )",
              ")"
            ],
            "lineageTag": "01c722a7-9c3f-49d1-9da3-0995c14ca6f9"
          },
          {
            "name": "Last 60 Minutes CarryForwardBurndown %",
            "expression": "[Last 60 Minutes CarryForwardBurndown]/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "c756da28-c333-4f24-8950-b7191e212a4a"
          },
          {
            "name": "Last 10 Minutes CumulativeCarryForward",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( TimePointOveragesByWorkloads[CumulativeCarryForward] ),",
              "    FILTER (",
              "        TimePointOveragesByWorkloads,",
              "        TimePointOveragesByWorkloads[WindowStartTime] >= MAX(TimePoints[TimePoint]) - TIME(0, 10, 0) ",
              "    )",
              ")"
            ],
            "lineageTag": "903b2e3a-c9b3-4c98-a0e7-0fea745c3291"
          },
          {
            "name": "Last 10 Minutes CumulativeCarryForward %",
            "expression": "[Last 10 Minutes CumulativeCarryForward]/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "02dc992e-5ec5-4d87-a822-3b628c640c27"
          },
          {
            "name": "Last 10 Minutes CarryForwardAdd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( TimePointOveragesByWorkloads[CarryForwardAdd] ),",
              "    FILTER (",
              "        TimePointOveragesByWorkloads,",
              "        TimePointOveragesByWorkloads[WindowStartTime] >= MAX(TimePoints[TimePoint]) - TIME(0, 10, 0) ",
              "    )",
              ")"
            ],
            "lineageTag": "ab0afb4a-d6c9-43a9-8147-768cdc9d82eb"
          },
          {
            "name": "Last 10 Minutes CarryForwardAdd %",
            "expression": "[Last 10 Minutes CarryForwardAdd]/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "a2c00431-4371-487f-b25b-bbc03d5fb0f9"
          },
          {
            "name": "Last 10 Minutes CarryForwardBurndown",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( TimePointOveragesByWorkloads[CarryForwardBurndown] ),",
              "    FILTER (",
              "        TimePointOveragesByWorkloads,",
              "        TimePointOveragesByWorkloads[WindowStartTime] >= MAX(TimePoints[TimePoint]) - TIME(0, 10, 0) ",
              "    )",
              ")"
            ],
            "lineageTag": "6493f95e-5f19-473c-88ea-0d10779a03f7"
          },
          {
            "name": "Last 10 Minutes CarryForwardBurndown %",
            "expression": "[Last 10 Minutes CarryForwardBurndown]/[Timepoint SKU CU CarryOver]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "daf94c32-7944-4504-b185-e77b161dc088"
          },
          {
            "name": "Last Cumulative Carry Over T2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE ( SUM ( TimePoint2OveragesByWorkloads[CumulativeCarryForward] ), TimePoint2OveragesByWorkloads[WindowStartTime] == MAX(TimePoints2[TimePoint]))"
            ],
            "lineageTag": "3e2947ca-da73-44cd-9343-694337e804a5"
          },
          {
            "name": "Timepoint SKU CU CarryOver T2",
            "expression": [
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints2'[TimePoint])",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('TimePoint2OveragesByWorkloads'[BaseCapacityUnits]) ",
              "    VAR AutoScaleCoreCount = MAX(TimePoint2OveragesByWorkloads[AutoScaleCapacityUnits])",
              "    RETURN (BaseCoreCount * 30) //+ IF(AutoScaleCoreCount>0,AutoScaleCoreCount*30,0)",
              "RETURN CU"
            ],
            "formatString": "0",
            "lineageTag": "27899a0c-2ca3-4838-803b-a1f021f8995f"
          },
          {
            "name": "Last Cumulative Carry Over T2 %",
            "expression": "[Last Cumulative Carry Over T2]/[Timepoint SKU CU CarryOver T2]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "1ac04082-84f9-4d57-ab21-7a3083cb7bdf"
          },
          {
            "name": "Last 24 hrs Cumulative CarryForward % T2",
            "expression": "SUM(TimePoint2OveragesByWorkloads[CumulativeCarryForward])/[Timepoint SKU CU CarryOver T2]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "47b9a8b1-92db-4829-bd06-b94b711033dc"
          },
          {
            "name": "Last 24 hrs CarryForward Burndown % T2",
            "expression": "SUM(TimePoint2OveragesByWorkloads[CarryForwardBurndown])/[Timepoint SKU CU CarryOver T2]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "8d5fdf86-c85d-473e-8515-eba477d54978"
          },
          {
            "name": "Last 24 hrs CarryForward Add % T2",
            "expression": "SUM(TimePoint2OveragesByWorkloads[CarryForwardAdd])/[Timepoint SKU CU CarryOver T2]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "0a694486-3ac3-4b06-bddc-4529f89d3b9d"
          },
          {
            "name": "Last 10 Minutes CarryForwardAdd % T2",
            "expression": [
              "",
              "",
              "var carryForwardAdd = ",
              "    CALCULATE (",
              "    SUM ( TimePoint2OveragesByWorkloads[CarryForwardAdd] ),",
              "    FILTER (",
              "        TimePoint2OveragesByWorkloads,",
              "        TimePoint2OveragesByWorkloads[WindowStartTime] >= MAX(TimePoints2[TimePoint]) - TIME(0, 10, 0) ",
              "    )",
              ")",
              "",
              "return DIVIDE(carryForwardAdd,[Timepoint SKU CU CarryOver T2]",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "f74dfe32-0173-4aac-a377-de61b01ff334"
          },
          {
            "name": "Last 10 Minutes CarryForwardBurndown % T2",
            "expression": [
              "",
              "",
              "var CarryForwardBurndown = ",
              "    CALCULATE (",
              "    SUM ( TimePoint2OveragesByWorkloads[CarryForwardBurndown] ),",
              "    FILTER (",
              "        TimePoint2OveragesByWorkloads,",
              "        TimePoint2OveragesByWorkloads[WindowStartTime] >= MAX(TimePoints2[TimePoint]) - TIME(0, 10, 0) ",
              "    )",
              ")",
              "",
              "return DIVIDE(CarryForwardBurndown,[Timepoint SKU CU CarryOver T2]",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "ca537e9a-1294-4296-bfaf-12275a2ebddc"
          },
          {
            "name": "Last 10 Minutes CumulativeCarryForward % T2",
            "expression": [
              "",
              "",
              "var CumulativeCarryForward = ",
              "    CALCULATE (",
              "    SUM ( TimePoint2OveragesByWorkloads[CumulativeCarryForward] ),",
              "    FILTER (",
              "        TimePoint2OveragesByWorkloads,",
              "        TimePoint2OveragesByWorkloads[WindowStartTime] >= MAX(TimePoints2[TimePoint]) - TIME(0, 10, 0) ",
              "    )",
              ")",
              "",
              "return DIVIDE(CumulativeCarryForward,[Timepoint SKU CU CarryOver T2]",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "fac645cf-b001-41ef-beb9-df00e4d4e674"
          },
          {
            "name": "Last 60 Minutes CarryForwardBurndown % T2",
            "expression": [
              "",
              "",
              "var CarryForwardBurndown = ",
              "    CALCULATE (",
              "    SUM ( TimePoint2OveragesByWorkloads[CarryForwardBurndown] ),",
              "    FILTER (",
              "        TimePoint2OveragesByWorkloads,",
              "        TimePoint2OveragesByWorkloads[WindowStartTime] >= MAX(TimePoints2[TimePoint]) - TIME(0, 60, 0) ",
              "    )",
              ")",
              "",
              "return DIVIDE(CarryForwardBurndown,[Timepoint SKU CU CarryOver T2]",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "bc0fa778-ba03-4680-b6c2-e519f31ed4f6"
          },
          {
            "name": "Last 60 Minutes CarryForwardAdd % T2",
            "expression": [
              "",
              "",
              "var CarryForwardAdd = ",
              "    CALCULATE (",
              "    SUM ( TimePoint2OveragesByWorkloads[CarryForwardAdd] ),",
              "    FILTER (",
              "        TimePoint2OveragesByWorkloads,",
              "        TimePoint2OveragesByWorkloads[WindowStartTime] >= MAX(TimePoints2[TimePoint]) - TIME(0, 60, 0) ",
              "    )",
              ")",
              "",
              "return DIVIDE(CarryForwardAdd,[Timepoint SKU CU CarryOver T2]",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "101b5cb3-5c9d-46af-aea1-24d9cc34c89a"
          },
          {
            "name": "Last 60 Minutes CumulativeCarryForward % T2",
            "expression": [
              "",
              "",
              "var CumulativeCarryForward = ",
              "    CALCULATE (",
              "    SUM ( TimePoint2OveragesByWorkloads[CumulativeCarryForward] ),",
              "    FILTER (",
              "        TimePoint2OveragesByWorkloads,",
              "        TimePoint2OveragesByWorkloads[WindowStartTime] >= MAX(TimePoints2[TimePoint]) - TIME(0, 60, 0) ",
              "    )",
              ")",
              "",
              "return DIVIDE(CumulativeCarryForward,[Timepoint SKU CU CarryOver T2]",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "cef0a9b9-f809-43db-b058-0e701439b6da"
          },
          {
            "name": "Total Number of Workspaces",
            "displayFolder": "Onelake Measures",
            "expression": "DISTINCTCOUNT(StorageByWorkspacesandDay[WorkspaceId])",
            "formatString": "#,0",
            "lineageTag": "28157cf4-3fc0-4627-95fe-17d1dff0506a"
          },
          {
            "name": "Current Storage in GB",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "CALCULATE (",
              "                SUM(StorageByWorkspacesandHour[Utilization (GB)]),",
              "                    FILTER ( StorageByWorkspacesandHour, StorageByWorkspacesandHour[DateTime] = (MAX(StorageByWorkspacesandHour[DateTime]))))"
            ],
            "lineageTag": "42a2696a-7de4-4db6-bdf5-cf3cdb16f9d2"
          },
          {
            "name": "Dynamic M1 Cumulative Utilization (GB) by Workspace",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "        VAR isFiltered_Hour = ISFILTERED ( 'DateTime'[Hour Start] )",
              "        //VAR isFiltered_Day = ISFILTERED('Dates'[Date])  ",
              "        //VAR isFiltered_Workspace = ISFILTERED(Workspaces[WorkspaceId])",
              "",
              "VAR Result =  ",
              "SWITCH(TRUE(),",
              "        isFiltered_Hour, sum(StorageByWorkspacesandHour[StaticStorageInGb]),",
              "        sum(StorageByWorkspacesandDay[StaticStorageInGb]))",
              "",
              "Return Result"
            ],
            "lineageTag": "ddb76496-080a-45ea-b12b-a6b29d3d9a56"
          },
          {
            "name": "Cumulative Utilization (GB) % by Workspace",
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "VAR base = [Dynamic M1 Cumulative Utilization (GB) by Workspace]",
              "VAR baseparent = CALCULATE([Total Cumulative Storage in GB],",
              "        ALL ( 'Workspaces'[WorkspaceId]),",
              "        ALL(Workspaces[WorkspaceName]),",
              "        ALL(Workspaces[WorkspaceProvisionState]),",
              "        ALL('Billing type'[Billing type]),",
              "        ALL(OperationForStorage[OperationName])",
              "     )",
              "VAR Percentage = DIVIDE ( base, baseparent )",
              " RETURN  IF( base == 0, 0, Percentage)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "52d1c963-18d7-46d2-8020-9313be189177"
          },
          {
            "name": "Avg Cumulative Static Storage Daily",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "VAR SelectedDate = SELECTEDVALUE(Dates[Date])",
              "VAR FirstDateOfSlicer = CALCULATE(FIRSTDATE(Dates[Day]), ALLEXCEPT(Dates,Dates[Day]))",
              "VAR HoursInMonth = DAY(EOMONTH(SelectedDate, 0)) * 24 ",
              "",
              "VAR CumulativeStorage =",
              "    CALCULATE ",
              "    (",
              "        SUMX(StorageByWorkspacesandHour, StorageByWorkspacesandHour[StaticStorageInGb]),",
              "        'Dates'[Date] <= SelectedDate && Dates[Date] >= FirstDateOfSlicer",
              "    )",
              "",
              "RETURN",
              "    IF(CumulativeStorage > 0, CumulativeStorage , BLANK())"
            ],
            "lineageTag": "c6e55cdf-a97b-4dfb-9386-e954fe5befb1"
          },
          {
            "name": "Avg Cumulative Static Storage Hourly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "VAR SelectedDate = SELECTEDVALUE(Dates[Date])",
              "//VAR FirstDateOfSlicer = CALCULATE(FIRSTDATE(Dates[Date]), ALLEXCEPT(Dates, Dates[Day Month]))",
              "VAR FirstDateOfSlicer = CALCULATE(FIRSTDATE(Dates[Day]), ALLEXCEPT(Dates,Dates[Day]))",
              "VAR HoursInMonth = DAY(EOMONTH(SelectedDate, 0)) * 24",
              "VAR CumulativeStorage =",
              "    CALCULATE (",
              "        SUMX(StorageByWorkspacesandHour,StorageByWorkspacesandHour[Utilization (GB)]/HoursInMonth),",
              "        FILTER (",
              "            ALL(DateTime),",
              "            DateTime[Date] <= SelectedDate &&",
              "            DateTime[Hour Start] <= MAX(StorageByWorkspacesandHour[DateTime])",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF(CumulativeStorage > 0, CumulativeStorage, BLANK())",
              ""
            ],
            "lineageTag": "3268cc06-3dc2-47f2-8905-ed41a68b5fdb"
          },
          {
            "name": "Billed (GB)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Onelake Measures",
            "expression": "SUM(StorageByWorkspacesandDay[StaticStorageInGb])",
            "lineageTag": "85984014-a38c-4809-8a9e-7d923e6c5b24"
          },
          {
            "name": "Billed (GB) %",
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "",
              "VAR base = [Billed (GB)]",
              "VAR baseparent = CALCULATE(SUM(StorageByWorkspacesandDay[StaticStorageInGb]),",
              "        ALL ( 'Workspaces'[WorkspaceId]),",
              "        ALL(Workspaces[WorkspaceName]),",
              "        ALL(Workspaces[WorkspaceProvisionState]),",
              "        ALL('Billing type'[Billing type]),",
              "        ALL(OperationForStorage[OperationName])",
              "     )",
              "VAR Percentage = DIVIDE ( base, baseparent )",
              " RETURN  IF(NOT(ISBLANK(base)) && ISBLANK(Percentage),0,Percentage)"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "a0c822c7-c951-40ad-bf07-a69047d3b41f"
          },
          {
            "name": "Dynamic M1 Cumulative Utilization (GB) by Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "        VAR isFiltered_Hour = ISFILTERED ('DateTime'[Hour Start] )",
              "        VAR isFiltered_Day = ISFILTERED('Dates'[Date])  ",
              "        VAR isFiltered_Day_Month = ISFILTERED('Dates'[Day]) ",
              "        VAR isFiltered_1st_Day_of_Week = ISFILTERED('Dates'[First Day of Week])",
              "",
              "RETURN ",
              "SWITCH(TRUE(),",
              "         isFiltered_Day && not isFiltered_Hour, [Avg Cumulative Static Storage Daily],",
              "         isFiltered_Hour, [Avg Cumulative Static Storage Hourly],",
              "        isFiltered_Day_Month || isFiltered_1st_Day_of_Week ,[Avg Cumulative Static Storage Daily],",
              "        0)"
            ],
            "lineageTag": "3fd927c3-d06f-476c-801f-c0554211ac51"
          },
          {
            "name": "Dynamic Text for OneLake",
            "displayFolder": "Onelake Measures",
            "expression": "IF([SKU Check],\"Onelake storage is not supported for EM/A SKUs. Please select another capacity.\",\"\")",
            "lineageTag": "e8dec9f8-380d-4a74-bc8d-b4ab52e98d4c"
          },
          {
            "name": "SKU Check",
            "displayFolder": "Onelake Measures",
            "expression": [
              "",
              "VAR SKUList = {\"EM3\", \"EM2\", \"EM1\", \"A8\", \"A7\", \"A6\", \"A5\", \"A4\", \"A3\", \"A2\", \"A1\"}",
              "VAR SelectedSKU = SELECTEDVALUE(Capacities[sku])",
              "RETURN",
              "IF(SelectedSKU IN SKUList, TRUE(), FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "aac5ac3d-24de-4e35-96ce-6c11d605b595"
          },
          {
            "name": "Dynamic M1 Throttling (min)",
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        //VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "        RETURN ",
              "            SWITCH (",
              "                TRUE (),",
              "                not isFiltered_Hour && not isFiltered_Op && not isFiltered_Day,SUM ( \t\t'MetricsByItem'[Throttling (min)] ),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day,SUM ( \t\t'MetricsByItemandDay'[Throttling (min)] )  ,",
              "                isFiltered_Op && not isFiltered_Day,SUM ( \t\t'MetricsByItemandOperation'[Throttling (min)] ),",
              "                not isFiltered_Hour &&  isFiltered_Op,SUM ( \t\t'MetricsByItemandOperationandDay'[Throttling (min)] ),",
              "                SUM ( 'MetricsByItemandOperationandHour'[Throttling (min)] )               ",
              "",
              "                )",
              ""
            ],
            "formatString": "0.0000",
            "lineageTag": "6feb1f3d-630a-4df3-a8c5-249b956bec5f"
          },
          {
            "name": "Last Carry Over Add",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE ( SUM ( TimePointOveragesByWorkloads[CarryForwardAdd] ), TimePointOveragesByWorkloads[WindowStartTime] == MAX(TimePoints[TimePoint]))"
            ],
            "lineageTag": "3eba0d27-3224-42a3-9f97-6ab9efa02c66"
          },
          {
            "name": "Last Carry Over Add %",
            "expression": "[Last Carry Over Add]/[Timepoint SKU CU CarryOver]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7cab5876-15fb-4a5c-b567-fd5d1da14f53"
          },
          {
            "name": "Last Carry Over Burndown %",
            "expression": "[Last Carry Over Burdown]/[Timepoint SKU CU CarryOver]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fb17866a-15b0-4a85-b8d5-fbd52505fd79"
          },
          {
            "name": "Last Carry Over Add T2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE ( SUM ( TimePoint2OveragesByWorkloads[CarryForwardAdd] ), TimePoint2OveragesByWorkloads[WindowStartTime] == MAX(TimePoints2[TimePoint]))"
            ],
            "lineageTag": "4e5c05e4-fb1f-43a1-be1e-3fd34777451d"
          },
          {
            "name": "Last Carry Over Add T2 %",
            "expression": "[Last Carry Over Add T2]/[Timepoint SKU CU CarryOver T2]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ced8822e-a3ac-41cc-b69f-6f987de4a635"
          },
          {
            "name": "Last Carry Over Burdown T2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE ( SUM ( TimePoint2OveragesByWorkloads[CarryForwardBurndown] ), TimePoint2OveragesByWorkloads[WindowStartTime] == MAX(TimePoints2[TimePoint]))"
            ],
            "lineageTag": "a0bd3491-1c03-428c-93d5-da920ba33f52"
          },
          {
            "name": "Last Carry Over Burndown T2 %",
            "expression": "[Last Carry Over Burdown T2]/[Timepoint SKU CU CarryOver T2]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "21c370b8-0793-488e-8517-c49e65935bee"
          },
          {
            "name": "IsWorkloadInCapacity",
            "expression": [
              "",
              "IF(",
              "    COUNTROWS(FILTER(WorkloadforStorage,( WorkloadforStorage[capacityId] = SELECTEDVALUE(Capacities[capacityId])) && (WorkloadforStorage[WorkloadKind] = MAX(Workloads[WorkloadKind])))) > 0,",
              "    1,",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "86d58fe3-08cf-4a56-acb1-699a3ceb1e11"
          },
          {
            "name": "IsWorkloadInWorkspace",
            "expression": [
              "",
              "IF(",
              "    COUNTROWS(FILTER(StorageByWorkspacesandHour,( StorageByWorkspacesandHour[PremiumCapacityId] = SELECTEDVALUE(Capacities[capacityId])) && (StorageByWorkspacesandHour[WorkloadKind] = MAX(Workloads[WorkloadKind])))) > 0,",
              "    1,",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fe0e4656-02bc-41e1-ba10-a6acf90dd172"
          },
          {
            "name": "IsOperationNameInCapacity",
            "expression": [
              "",
              "IF(",
              "    COUNTROWS(FILTER(StorageByWorkspacesandHour,( StorageByWorkspacesandHour[PremiumCapacityId] = SELECTEDVALUE(Capacities[capacityId])) && (StorageByWorkspacesandHour[StorageType] = MAX(OperationForStorage[StorageType])))) > 0,",
              "    1,",
              "    0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fa78de54-5b2d-4cd4-bf0e-52690f5ecf1d"
          },
          {
            "name": "Dynamic Text for Default Capacity",
            "expression": [
              "",
              "VAR capacityname = SELECTEDVALUE(Capacities[Capacity Name])",
              "RETURN",
              " IF(capacityname = \"select a capacity from dropdown\" || ISBLANK(capacityname) ,\"No capacity is selected. Please select a capacity in the slicer to see data in visuals.\",\"\")"
            ],
            "lineageTag": "3fa0c0a4-215d-4bf2-b6fa-2944b2fd4783"
          },
          {
            "name": "BackgroundColour",
            "expression": "IF(SELECTEDVALUE(Capacities[Capacity Name]) = \"Select a capacity from dropdown\" || ISBLANK(SELECTEDVALUE(Capacities[Capacity Name])) ,\"#FFFFFF\",\"#FFFFFF00\")",
            "lineageTag": "bb5e1d15-3aa1-4e58-9819-01244617100f"
          },
          {
            "name": "Dynamic Text for Default Capacity 2",
            "expression": [
              "",
              "VAR capacityname = SELECTEDVALUE(Capacities[Capacity Name])",
              "RETURN",
              " IF(capacityname <> \"Select a capacity from dropdown1\" && NOT(ISBLANK(capacityname)) ,\"Pick a capacity from the Capacity name slicer to see data. All visuals on the page will refresh each time a capacity is picked. Learn how to use this page by clicking the info button. \",\"\")"
            ],
            "lineageTag": "be68a5fc-c094-4981-81b6-907ffae295d5"
          },
          {
            "name": "Dynamic Visual border",
            "expression": [
              "",
              "VAR capacityname = SELECTEDVALUE(Capacities[Capacity Name])",
              "RETURN",
              " IF(capacityname = \"select a capacity from dropdown\" || ISBLANK(capacityname), \"Yes\",\"No\")"
            ],
            "lineageTag": "10853e9e-bc65-42c7-94de-702555676e4e"
          },
          {
            "name": "Dynamic Text for Default Capacity 3",
            "expression": [
              "",
              "VAR capacityname = SELECTEDVALUE(Capacities[Capacity Name])",
              "RETURN",
              " IF(capacityname = \"select a capacity from dropdown\" || ISBLANK(capacityname) ,\"For New Users: Please wait for a minute and select a capacity in the slicer to see data.\",\"\")"
            ],
            "lineageTag": "732933d7-3db8-4f7a-9111-de9162cd413c"
          },
          {
            "name": "Dynamic Text for Default Capacity 4",
            "expression": [
              "",
              "VAR capacityname = SELECTEDVALUE(Capacities[Capacity Name])",
              "RETURN",
              " IF(capacityname = \"select a capacity from dropdown\" || ISBLANK(capacityname) ,\"For Existing Users: Please wait for a minute and refresh the page to see data.\",\"\")"
            ],
            "lineageTag": "19e3d98d-1570-48b4-bcc5-7f4a689b00af"
          },
          {
            "name": "Last Expected burndown in minutes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Last Cumulative Carry Over]/(2 * [SKU CU by Timepoint Basecore]) ",
            "lineageTag": "b9d27256-3b1f-4b73-9d77-b83b7a388f42"
          },
          {
            "name": "Last Expected burndown in minutes T2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Last Cumulative Carry Over T2]/([SKU CU by Timepoint Basecore]*2) ",
            "lineageTag": "9d0a06d6-dba0-46b9-87e7-f5c2d9623493"
          },
          {
            "name": "Last 10 minutes Expected burndown in minutes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " var CumulativeCarryForward = ",
              "    CALCULATE (",
              "    SUM ( TimePointOveragesByWorkloads[CumulativeCarryForward] ),",
              "    FILTER (",
              "        TimePointOveragesByWorkloads,",
              "        TimePointOveragesByWorkloads[WindowStartTime] >= MAX(TimePoints[TimePoint]) - TIME(0, 10, 0) ",
              "    )",
              ")",
              "",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('TimePointOveragesByWorkloads'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30)",
              "",
              "Return",
              " CumulativeCarryForward/(2 * CU) "
            ],
            "lineageTag": "929ad531-53f6-4717-9ebe-d2e1f14f7781"
          },
          {
            "name": "Last 10 minutes Expected burndown in minutes T2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " var CumulativeCarryForward = ",
              "    CALCULATE (",
              "    SUM ( TimePoint2OveragesByWorkloads[CumulativeCarryForward] ),",
              "    FILTER (",
              "        TimePoint2OveragesByWorkloads,",
              "        TimePoint2OveragesByWorkloads[WindowStartTime] >= MAX(TimePoints2[TimePoint]) - TIME(0, 10, 0) ",
              "    )",
              ")",
              "",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('TimePoint2OveragesByWorkloads'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30)",
              "",
              "Return",
              " CumulativeCarryForward/(2 * CU) "
            ],
            "lineageTag": "8b16db40-1fe2-4469-87e9-e7c2668a0ec3"
          },
          {
            "name": "Last 24 hrs Expected burndown in minutes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " var CumulativeCarryForward = ",
              "SUM (TimePointOveragesByWorkloads[CumulativeCarryForward])",
              "",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('TimePointOveragesByWorkloads'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30)",
              "",
              "Return",
              " CumulativeCarryForward/(2 * CU) "
            ],
            "lineageTag": "5bdf70dd-515d-4adf-ae44-7d5613423192"
          },
          {
            "name": "Last 60 minutes Expected burndown in minutes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " var CumulativeCarryForward = ",
              "    CALCULATE (",
              "    SUM ( TimePointOveragesByWorkloads[CumulativeCarryForward] ),",
              "    FILTER (",
              "        TimePointOveragesByWorkloads,",
              "        TimePointOveragesByWorkloads[WindowStartTime] >= MAX(TimePoints[TimePoint]) - TIME(0, 60, 0) ",
              "    )",
              ")",
              "",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('TimePointOveragesByWorkloads'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30)",
              "",
              "Return",
              " CumulativeCarryForward/(2 * CU) "
            ],
            "lineageTag": "9348bb9b-ff41-40ad-9326-3ef45d7c67ab"
          },
          {
            "name": "Last 60 minutes Expected burndown in minutes T2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " var CumulativeCarryForward = ",
              "    CALCULATE (",
              "    SUM ( TimePoint2OveragesByWorkloads[CumulativeCarryForward] ),",
              "    FILTER (",
              "        TimePoint2OveragesByWorkloads,",
              "        TimePoint2OveragesByWorkloads[WindowStartTime] >= MAX(TimePoints2[TimePoint]) - TIME(0, 60, 0) ",
              "    )",
              ")",
              "",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('TimePoint2OveragesByWorkloads'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30)",
              "",
              "Return",
              " CumulativeCarryForward/(2 * CU) "
            ],
            "lineageTag": "7be18633-a71e-4703-a91d-0d6aab471a12"
          },
          {
            "name": "Last 24 hrs Expected burndown in minutes T2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " var CumulativeCarryForward = ",
              " SUM(TimePoint2OveragesByWorkloads[CumulativeCarryForward])",
              "",
              "VAR CU = ",
              "    VAR BaseCoreCount = MAX('TimePoint2OveragesByWorkloads'[BaseCapacityUnits]) ",
              "    RETURN (BaseCoreCount * 30)",
              "",
              "Return",
              " CumulativeCarryForward/(2 * CU) "
            ],
            "lineageTag": "7e43788f-0c21-4f5a-ac38-27b1633fdc14"
          },
          {
            "name": "Dynamic M1 Failed Op Count",
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        //VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "",
              "        RETURN ",
              "            SWITCH (",
              "                TRUE (),",
              "                not isFiltered_Hour && not isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItem'[count_failure_operations] ),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day,SUM ( 'MetricsByItemandDay'[count_failure_operations] )  ,",
              "                isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItemandOperation'[count_failure_operations] ),",
              "                not isFiltered_Hour &&  isFiltered_Op,SUM ( 'MetricsByItemandOperationandDay'[count_failure_operations] ),",
              "                SUM ( 'MetricsByItemandOperationandHour'[count_failure_operations] )               ",
              "                )"
            ],
            "formatString": "0",
            "lineageTag": "920f0d30-96cd-4393-8cae-ce05e72bb139"
          },
          {
            "name": "Dynamic M1 InProgress Op Count",
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        //VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "        ",
              "        RETURN ",
              "            SWITCH (",
              "                TRUE (),",
              "                not isFiltered_Hour && not isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItem'[count_InProgress_operations] ),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day,SUM ( 'MetricsByItemandDay'[count_InProgress_operations] )  ,",
              "                isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItemandOperation'[count_InProgress_operations] ),",
              "                not isFiltered_Hour &&  isFiltered_Op,SUM ( 'MetricsByItemandOperationandDay'[count_InProgress_operations] ),",
              "                SUM ( 'MetricsByItemandOperationandHour'[count_InProgress_operations] )               ",
              "                )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "295c4903-456d-4e19-9460-7af2c3b93d8c"
          },
          {
            "name": "Dynamic M1 Invalid Op Count",
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        //VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "        ",
              "        RETURN ",
              "            SWITCH (",
              "                TRUE (),",
              "                not isFiltered_Hour && not isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItem'[count_Invalid_operations] ),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day,SUM ( 'MetricsByItemandDay'[count_Invalid_operations] )  ,",
              "                isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItemandOperation'[count_Invalid_operations] ),",
              "                not isFiltered_Hour &&  isFiltered_Op,SUM ( 'MetricsByItemandOperationandDay'[count_Invalid_operations] ),",
              "                SUM ( 'MetricsByItemandOperationandHour'[count_Invalid_operations] )               ",
              "                )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bfe75924-3bea-49b3-aabd-c97669f98bc9"
          },
          {
            "name": "Dynamic M1 Rejected Op Count",
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        //VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "        ",
              "        RETURN ",
              "            SWITCH (",
              "                TRUE (),",
              "                not isFiltered_Hour && not isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItem'[count_rejected_operations] ),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day,SUM ( 'MetricsByItemandDay'[count_rejected_operations] )  ,",
              "                isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItemandOperation'[count_rejected_operations] ),",
              "                not isFiltered_Hour &&  isFiltered_Op,SUM ( 'MetricsByItemandOperationandDay'[count_rejected_operations] ),",
              "                SUM ( 'MetricsByItemandOperationandHour'[count_rejected_operations] )               ",
              "                )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "645ebe0c-787d-4ac3-8f54-537ff7a52cb8"
          },
          {
            "name": "Dynamic M1 Successful Op Count",
            "expression": [
              "",
              "",
              "        VAR isFiltered_Hour =",
              "            ISFILTERED ( 'DateTime'[Hour Start] )",
              "        VAR isFiltered_Op =",
              "            ISFILTERED ( 'OperationNames'[OperationName])",
              "            ",
              "        VAR isFiltered_Day = ISFILTERED(Dates[Date])   ",
              "        //VAR hasOneFilter_Day = HASONEFILTER(Dates[Date])",
              "        VAR myOperationName = SELECTEDVALUE('OperationNames'[OperationName],\"\")",
              "        VAR myMetric = SELECTEDVALUE('Metrics'[Metric])",
              "        ",
              "        RETURN ",
              "            SWITCH (",
              "                TRUE (),",
              "                not isFiltered_Hour && not isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItem'[count_successful_operations] ),",
              "\t\t\t    not isFiltered_Hour && not isFiltered_Op && isFiltered_Day,SUM ( 'MetricsByItemandDay'[count_successful_operations] )  ,",
              "                isFiltered_Op && not isFiltered_Day,SUM ( 'MetricsByItemandOperation'[count_successful_operations] ),",
              "                not isFiltered_Hour &&  isFiltered_Op,SUM ( 'MetricsByItemandOperationandDay'[count_successful_operations] ),",
              "                SUM ( 'MetricsByItemandOperationandHour'[count_successful_operations] )               ",
              "                )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "e87fa7a6-daa9-4b59-b800-6c8da8f6d8f5"
          },
          {
            "name": "Item virtualization status",
            "expression": "If ( MAX(Items[IsVirtualArtifactName]), \"True\", \"False\")",
            "lineageTag": "17517434-bf34-4acd-b5ae-8b0c1b7672b6"
          },
          {
            "name": "xCarryOver_cumulative",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR y = MAX('TimePointOverageDetail'[CumulativeCarryForward])",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('TimePointOverageDetail'[Peak20minCumulativeCarryForward])/1000",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )"
            ],
            "lineageTag": "9a13b38a-4104-49f0-981d-3cb545fac934"
          },
          {
            "name": "xBackground",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR y = MAX('CUDetail'[Background])",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('CUDetail'[Peak6minBackground])/1000",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )"
            ],
            "lineageTag": "3ef94806-0aca-4e6b-a8d2-4ec47deea78a"
          },
          {
            "name": "xBackgroundPreview",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR y = MAX('CUDetail'[BackgroundPreview])",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('CUDetail'[Peak6minBackgroundPreview])/1000",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )"
            ],
            "lineageTag": "9db2ae8b-8272-4856-9736-5c270144525c"
          },
          {
            "name": "xInteractive",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR x =[xBackground]",
              "VAR y = MAX('CUDetail'[Interactive]) + IF(NOT ISBLANK(x) , 0)",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('CUDetail'[Peak6minInteractive])/1000",
              "",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )",
              "",
              ""
            ],
            "formatString": "0.00",
            "lineageTag": "f5655d13-dc08-486b-a121-375b256f54bb"
          },
          {
            "name": "xInteractivePreview",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR x =[xBackgroundPreview]",
              "VAR y = MAX('CUDetail'[InteractivePreview]) + IF(NOT ISBLANK(x) , 0)",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('CUDetail'[Peak6minInteractivePreview])/1000",
              "",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )"
            ],
            "lineageTag": "5246528e-7d7b-4057-80c7-ee3811d2ce39"
          },
          {
            "name": "SKU CU by TimePoint Timepoint Card Preview 2",
            "expression": [
              "",
              "",
              "VAR TimePoint = SELECTEDVALUE('TimePoints2'[TimePoint])",
              "",
              "VAR CU =",
              "",
              "    VAR BaseCoreCount = MAX('TimePoint2CUDetail'[BaseCapacityUnits])",
              "",
              "    VAR AutoScaleCoreCount = MAX(TimePoint2CUDetail[AutoScaleCapacityUnits])",
              "",
              "    RETURN (BaseCoreCount * 30) + IF(AutoScaleCoreCount>0,AutoScaleCoreCount*30)",
              "",
              "RETURN CU"
            ],
            "formatString": "0",
            "lineageTag": "99d399df-ebb4-4834-9adb-13bb46364e52"
          },
          {
            "name": "Workspace virtualization status",
            "expression": "If ( MAX(Items[IsVirtualWorkspaceName]), \"True\", \"False\")",
            "lineageTag": "ed217d8f-bfeb-4889-9751-58163c0ac72d"
          },
          {
            "name": "Dynamic InteractiveDelay %",
            "expression": [
              "",
              "",
              "VAR y = MAX('CUDetail'[Interactive Delay %])",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('CUDetail'[Peak6min Interactive Delay %])",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5c584a9e-b943-463a-bbca-cdba45537483"
          },
          {
            "name": "Dynamic InteractiveRejection %",
            "expression": [
              "",
              "",
              "VAR y = MAX('CUDetail'[Interactive Rejection %])",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('CUDetail'[Peak6min Interactive Rejection %])",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e90eafaa-25ed-4be9-a88d-5a295dd37078"
          },
          {
            "name": "Dynamic BackgroundRejection %",
            "expression": [
              "",
              "",
              "VAR y = MAX('CUDetail'[Background Rejection %])",
              "VAR tp = SELECTEDVALUE('TimePoints'[TimePoint])",
              "VAR df = HASONEVALUE('Dates'[Date])",
              "",
              "VAR z =  MAX('CUDetail'[Peak6min Background Rejection %])",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        df, y ,",
              "        z",
              "        )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f0cda2b1-2e2c-4581-b56e-4b42a1fdc56c"
          },
          {
            "name": "Interactive delay threshold",
            "expression": [
              "",
              "VAR x = [Dynamic InteractiveDelay %]",
              "RETURN if(not isblank(x),1)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c83b1a81-81bf-4171-9695-a31690ed343e"
          },
          {
            "name": "Interactive rejection threshold",
            "expression": [
              "",
              "VAR x = [Dynamic InteractiveRejection %]",
              "RETURN if(not isblank(x),1)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fff46afd-3280-47a8-8676-cb3f6dacb995"
          },
          {
            "name": "Background rejection threshold",
            "expression": [
              "",
              "VAR x = [Dynamic BackgroundRejection %]",
              "RETURN if(not isblank(x),1)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4d70a655-6700-4a0d-85fb-35264fd8acbb"
          },
          {
            "name": "Overage reference line",
            "expression": [
              "",
              "VAR x = [xCarryOver_Cumulative %]",
              "RETURN if(not isblank(x),0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6be42b39-2e8d-4a00-8e5e-014893996cd8"
          }
        ],
        "partitions": [
          {
            "name": "All Measures-856e677e-e294-41aa-84a0-74c1c4fd46ff",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b93fc691-3c3d-4a1e-8069-56eec00ef1b6",
            "sourceColumn": "Metric",
            "summarizeBy": "none"
          },
          {
            "name": "SortID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ebf8d624-6845-4dee-a4af-fb72ff125438",
            "sourceColumn": "SortID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "1fa0ac3e-2193-4eb1-ac68-77d81563e86c",
        "partitions": [
          {
            "name": "Metrics-3fd1e7f2-5e56-4f84-a221-50fa79dfca6b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcg5V0lEyVIrViVZyKS1KLMnMzwMKGIEFQotTi4qBPGMwzzvAE8QxAXP8C1IhikFCpkqxsQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, SortID = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Metric\", type text}, {\"SortID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTime",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3c5c6990d4d2456297fc5e680da2bbc2"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dc2c605d-f7f8-4c4a-b46f-92331d579a96",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Hour Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "H",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ea7fa41c-29d6-4b64-a2e7-479c165a5e17",
            "sourceColumn": "[Hour Start]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Hour End",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8758cb35-3d7d-43cb-ab27-759f7f905a65",
            "sourceColumn": "[Hour End]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Hour Start Long",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-MM-dd hh:mm",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "38d5bc47-f353-4767-8a41-b07820b63035",
            "sourceColumn": "[Hour Start Long]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "23b04518-523b-43bf-b743-e8e861ef8efa",
        "partitions": [
          {
            "name": "DateTime-7dcba463-f237-44bd-9651-17a496b0c08b",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "\tSELECTCOLUMNS(",
                "\t\tGENERATE(",
                "\t\t\tFILTER('Dates',[Date]>=TODAY()-30),",
                "\t\t\tGENERATESERIES(0,23)",
                "\t\t\t) ,",
                "\t\t\"Date\" \t\t , [Date] ,",
                "\t\t\"Hour Start\" , [Date] + TIME([Value],\t 0,0) ,",
                "\t\t\"Hour End\" \t , [Date] + TIME([Value]   +1,0,0),",
                "        \"Hour Start Long\" , [Date] + TIME([Value],\t 0,0)",
                "\t\t)"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ItemsThrottled",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "187ad974ba5d4c098ae16f7e18ef57bf"
          }
        ],
        "columns": [
          {
            "name": "capacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fe97d680-9c61-42b9-aea0-f7e1807b1280",
            "sourceColumn": "Items[capacityId]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2bfe39ba-ebde-42bc-8087-379f8308d7fe",
            "sourceColumn": "Items[ItemId]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ItemKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "637731c0-12b9-41c4-8c30-9355ae40e11f",
            "sourceColumn": "Items[ItemKind]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ItemName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e2c88c9a-f105-4086-a4a6-368460074224",
            "sourceColumn": "Items[ItemName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "dcount_Identity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "79f3df82-9dfd-499d-8ae2-735bc0011aa4",
            "sourceColumn": "Items[dcount_Identity]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "054d3a63-6dc5-4fbc-8f44-e6bd7855802b",
            "sourceColumn": "Items[Timestamp]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b4e90dc2-4a17-4b61-8d8b-9e6cf7340b92",
            "sourceColumn": "Items[WorkspaceId]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WorkspaceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e6f0e7a3-8e75-4c9b-b97e-51a461fa98ce",
            "sourceColumn": "Items[WorkspaceName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Billable type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6ae3f63d-feb9-4647-a954-f1442411e1cf",
            "sourceColumn": "Items[Billable type]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsVirtualArtifactName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8e15b582-e47a-465f-b6aa-705e649d4a55",
            "sourceColumn": "Items[IsVirtualArtifactName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsVirtualWorkspaceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f0664bf9-8c1f-400f-92f7-d67ad12418e4",
            "sourceColumn": "Items[IsVirtualWorkspaceName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsVirtualArtifactStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "44299498-1ca2-43ad-972f-fb784cb30e4a",
            "sourceColumn": "Items[IsVirtualArtifactStatus]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsVirtualWorkspaceStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "423ee257-a0c0-4b6d-8b00-5b01ca30683d",
            "sourceColumn": "Items[IsVirtualWorkspaceStatus]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a54828fc-bf04-472a-90bf-a9f2586cd05a",
            "sourceColumn": "Items[UniqueKey]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ItemKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f43ad365-cc8d-4eb6-af6e-c65db552f113",
            "sourceColumn": "Items[ItemKey]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5f594aed-2a77-4053-af3b-33ba48b3bd6e",
        "partitions": [
          {
            "name": "ItemsThrottled-f93e56fb-f33b-4bff-83c4-bcd2728f0a7e",
            "mode": "import",
            "source": {
              "expression": "Items",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "MetricsByItemandDay",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "22363f2c-3009-471f-8250-fb685d20c894",
            "sourceColumn": "DateTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "63e0b81f-2269-44d6-909e-b61b9b32f6f9",
            "sourceColumn": "Date",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "80406395-871e-4427-9469-e633299e0d65",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "00661aad-d01b-4317-8795-1057e22e0fa3",
            "sourceColumn": "ItemId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sum_CU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.000",
            "isHidden": true,
            "isNullable": false,
            "lineageTag": "2235f2d4-f387-4c87-ac59-b3a31eb6a309",
            "sourceColumn": "sum_CU",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "sum_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.000",
            "isHidden": true,
            "isNullable": false,
            "lineageTag": "7c1048d2-673c-4ff1-a7c5-4f66bcf545e9",
            "sourceColumn": "sum_duration",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2505dfe7-09d0-4b39-9184-a6c427cf3946",
            "sourceColumn": "count_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_users",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c001f00c-7c84-4c4a-b908-470e1e0c4238",
            "sourceColumn": "count_users",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_50",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "096c4a66-fac8-4122-89f0-4193a35b7524",
            "sourceColumn": "percentile_DurationMs_50",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_90",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad26a8dc-c4cb-4ed3-8b70-e0a6965193e3",
            "sourceColumn": "percentile_DurationMs_90",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "avg_DurationMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0783de79-4d35-4f59-906e-f1e3f9f1c41c",
            "sourceColumn": "avg_DurationMS",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Throttling (min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "93bbb43e-ccce-4afb-944a-424b575f5e15",
            "sourceColumn": "Throttling (min)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_failure_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f28d4699-e502-4ef3-ab7c-d482594e65d2",
            "sourceColumn": "count_failure_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_rejected_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f12644c8-2341-472f-bebb-3699422a6fe0",
            "sourceColumn": "count_rejected_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_successful_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8bf13c37-5c89-4f9c-9986-6e30c6bb8ddf",
            "sourceColumn": "count_successful_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_InProgress_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "deacfdbd-c69d-4d95-80b3-33fde8b74cef",
            "sourceColumn": "count_InProgress_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_cancelled_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f3a986dd-2565-43a1-a375-7a32f1d4ebfc",
            "sourceColumn": "count_cancelled_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_Invalid_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "33ef289d-2270-4481-a6a2-99acd93d9a12",
            "sourceColumn": "count_Invalid_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95f1704e-173e-41a0-a388-8bc68e2f4189",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e8448b96-98a0-4efa-9d8b-b340a9c32de2",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "469f3afc-3a89-4728-8230-c99ccdc28b5c",
        "partitions": [
          {
            "name": "MetricsByItemandDay-0889a6a4-32ff-4fd1-b4b7-4cedfe9b74af",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Metrics Preview",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"MetricsByArtifactAndDayForTridentV2\"),",
                "    #\"Uppercased Text\" = Table.TransformColumns(Source,{{\"ArtifactId\", Text.Upper, type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Uppercased Text\",{{\"ArtifactId\", \"ItemId\"}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Renamed Columns1\",{{\"sum_cpu\", \"sum_CU\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"sum_CU\", type number}, {\"sum_duration\", type number}}),",
                "    #\"Divided Column\" = Table.TransformColumns(#\"Changed Type\", {{\"sum_CU\", each _ / 1000,  Double.Type}}),",
                "    #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"sum_duration\", each _ / 1000,  Double.Type}})",
                "in",
                "    #\"Divided Column1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MetricsByItemandHour",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "6aa68c56-c76f-40b2-bc4a-c48958764035",
            "sourceColumn": "DateTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "855e8648-cd3c-458e-820a-4fad5c30ecb6",
            "sourceColumn": "Date",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cb417e26-3bc3-4061-9df7-c1ce923241f8",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b4f0d18c-d737-4f02-9d18-830b3b171de2",
            "sourceColumn": "ItemId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sum_CU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.000",
            "isHidden": true,
            "isNullable": false,
            "lineageTag": "14a25820-2574-4153-85fa-76b74447138c",
            "sourceColumn": "sum_CU",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "sum_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.000",
            "isHidden": true,
            "isNullable": false,
            "lineageTag": "f43fb5dd-b9e2-4c04-b590-9540a5a14701",
            "sourceColumn": "sum_duration",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a6271129-b04a-4ed5-a341-e02b2d32113d",
            "sourceColumn": "count_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_users",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "55715b03-4072-4ad9-92fc-f5c0b4151413",
            "sourceColumn": "count_users",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_50",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6ec81289-7af6-45ad-8d57-979305412d6e",
            "sourceColumn": "percentile_DurationMs_50",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_90",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "35eac3b1-2cd0-4c7f-8431-5500fa3fd9a3",
            "sourceColumn": "percentile_DurationMs_90",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "avg_DurationMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1a01a008-f0ba-42cb-9661-7e1e6e572ec7",
            "sourceColumn": "avg_DurationMS",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Throttling (min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67b0e09f-6411-46be-9060-b0225f9920f1",
            "sourceColumn": "Throttling (min)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_failure_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3245d1dc-0a08-4a2e-89bb-0018aedafc73",
            "sourceColumn": "count_failure_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_rejected_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "76b5fb47-a437-426c-b419-3954a1b8929c",
            "sourceColumn": "count_rejected_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_successful_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "96f5874d-9891-4f51-859e-ae7d77f96bc7",
            "sourceColumn": "count_successful_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_InProgress_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "817a9500-2f9a-4b8a-98be-300538a1832c",
            "sourceColumn": "count_InProgress_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_cancelled_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6035c93a-d2ce-4c3b-961c-2514c28bfb30",
            "sourceColumn": "count_cancelled_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_Invalid_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0bc9ac76-5c15-4305-8913-6aa80d053397",
            "sourceColumn": "count_Invalid_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e47a95fa-8f88-4bf5-857c-9406e0c96e42",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "81825fd4-a091-4f7c-8d9d-550b88c96c22",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "11b4fb0e-bb0a-47f6-8b3e-6560ba4728ab",
        "partitions": [
          {
            "name": "MetricsByItemandHour-f385cdcc-2340-4229-b25e-cf71db200e9f",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Metrics Preview",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"MetricsByArtifactsAndHourForTridentV2\"),",
                "    #\"Uppercased Text\" = Table.TransformColumns(Source,{{\"ArtifactId\", Text.Upper, type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Uppercased Text\",{{\"ArtifactId\", \"ItemId\"}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Renamed Columns1\",{{\"sum_cpu\", \"sum_CU\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"sum_CU\", type number}, {\"sum_duration\", type number}}),",
                "    #\"Divided Column\" = Table.TransformColumns( #\"Changed Type1\", {{\"sum_CU\", each _ / 1000, Double.Type}}),",
                "    #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"sum_duration\", each _ / 1000, Double.Type}})",
                "in",
                "    #\"Divided Column1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MetricsByItemandOperationandHour",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "2005e4a0-6ea5-4b55-bfa7-b8a9ecec85a4",
            "sourceColumn": "DateTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "a937711d-ba66-48d5-8a07-374f763a1832",
            "sourceColumn": "Date",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8a4d2738-4d6b-4e20-9bed-4de97bcdc6ad",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3c95c5a4-18d8-41bc-af55-b7ea5327fc65",
            "sourceColumn": "ItemId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "OperationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "05fb4708-f812-4b55-8389-7db6094a7c50",
            "sourceColumn": "OperationName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sum_CU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.000",
            "isHidden": true,
            "isNullable": false,
            "lineageTag": "ca8207c3-bd7d-4d13-b932-f91d2c622c40",
            "sourceColumn": "sum_CU",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "sum_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.000",
            "isHidden": true,
            "isNullable": false,
            "lineageTag": "fe087af0-3733-4a9d-95d4-865fe2c7e5e3",
            "sourceColumn": "sum_duration",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c478100b-4c18-4c85-99dc-3abfbdbed965",
            "sourceColumn": "count_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_users",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4911f19b-3a92-4181-a42a-1d9cc70e3806",
            "sourceColumn": "count_users",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_50",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "61d5fdd5-b726-47a8-be0e-e9d51a074492",
            "sourceColumn": "percentile_DurationMs_50",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_90",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3765a90e-be97-4fca-86bd-33fd2c7a8821",
            "sourceColumn": "percentile_DurationMs_90",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "avg_DurationMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e8543a86-1ef6-44f7-b438-8ec1cf632b79",
            "sourceColumn": "avg_DurationMS",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Throttling (min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56b4201c-83de-4316-bdbe-b45910a9c323",
            "sourceColumn": "Throttling (min)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_failure_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7b91e7a0-11ce-4e6b-a71e-d9a3a4d4b242",
            "sourceColumn": "count_failure_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_rejected_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b5594484-9aa0-468f-9d67-492fbacb634a",
            "sourceColumn": "count_rejected_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_successful_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f3f1d0c9-1d7f-408d-8b0c-b1aaa260f657",
            "sourceColumn": "count_successful_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_InProgress_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c33adea-4dc3-419a-9444-112ad531018a",
            "sourceColumn": "count_InProgress_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_cancelled_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0856493f-fac3-4156-b07b-0c2f445fe5c8",
            "sourceColumn": "count_cancelled_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_Invalid_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68adfb43-02e8-412e-a417-f70376435b1f",
            "sourceColumn": "count_Invalid_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad5892ea-ae02-4d1d-9a4d-13b68c04d839",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e7aadd0b-88ca-4212-864d-76a60d957156",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "3e3341ac-8f0b-4a27-8530-f06711307db1",
        "partitions": [
          {
            "name": "MetricsByItemandOperationandHour-4becd522-ee45-44cd-8371-2d00eef035c5",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Metrics Preview",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"MetricsByArtifactsAndOperationAndHourForTridentV2\"),",
                "    #\"Uppercased Text\" = Table.TransformColumns(Source,{{\"ArtifactId\", Text.Upper, type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Uppercased Text\",{{\"ArtifactId\", \"ItemId\"}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Renamed Columns1\",{{\"sum_cpu\", \"sum_CU\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"sum_CU\", type number}, {\"sum_duration\", Double.Type}}),",
                "    #\"Divided Column\" = Table.TransformColumns(#\"Changed Type\", {{\"sum_CU\", each _ / 1000,Double.Type}}),",
                "    #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"sum_duration\", each _ / 1000, type number}})",
                "in",
                "    #\"Divided Column1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Performance2daySnapshot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "68131fe5-cee8-49c9-ab18-098d10dfebfb",
            "sourceColumn": "ItemId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Performance delta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b50c3226-039c-44d8-b063-92188380bc1e",
            "sourceColumn": "Performance delta",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "OperationStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a0024ae0-5dc9-463c-a7a0-538b908ffda2",
            "sourceColumn": "OperationStartTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20d11a9a-0b26-425b-a360-d41b059b0857",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "deb87d7e-109d-403d-be6c-5d1f01b497c3",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "feae74d8-7da3-4567-8500-28880f0ff90c",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "7ff63740-80b3-4c64-b688-d0066032d680",
        "partitions": [
          {
            "name": "Performance2daySnapshot-3047152c-14ab-4580-81a9-4424aae6057d",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Performance",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"PerformanceTwoDaySnapshotForTridentV3\", null, null, \"14\"),",
                "    #\"Uppercased Text\" = Table.TransformColumns(Source,{{\"ArtifactId\", Text.Upper, type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Uppercased Text\",{{\"ArtifactId\", \"ItemId\"}}),",
                "    Custom1 = Table.TransformColumns(#\"Renamed Columns\", {{\"Performance delta\", each if Number.IsNaN(_) then null else _, type number}})",
                "in ",
                "    Custom1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePoint2InteractiveDetail",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OperationStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f7120552-3a3e-4ae7-b9cf-a73991c5e920",
            "sourceColumn": "OperationStartTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "OperationEndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6460ba26-8f9d-438b-a898-1d23a403736b",
            "sourceColumn": "OperationEndTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53f9c8f6-36c6-4260-a322-51f340b5a6d5",
            "sourceColumn": "Status",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ac48abe-c408-4912-9652-e3e389c98067",
            "sourceColumn": "Item",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c65033f5-02d0-4bc8-91b7-3128c366df08",
            "sourceColumn": "Operation",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "OperationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41fb6837-205c-4011-8bda-f023c18ccb02",
            "sourceColumn": "OperationId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c11e0c5c-c10c-4714-ab27-51a4793c6ba9",
            "sourceColumn": "User",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b1fc6983-d2fa-4a50-b99e-3b310cb8c9d9",
            "sourceColumn": "Start",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "End",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "efccb5c1-d0be-4906-b00b-c1c3b0d05ad9",
            "sourceColumn": "End",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Duration (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "16126ac0-80bb-4f01-8f76-6413dadb457e",
            "sourceColumn": "Duration (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Throttling (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "02da7e25-a3f9-4800-abe4-8b2315431cec",
            "sourceColumn": "Throttling (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "% of Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0abebff0-6b10-4907-91d2-4bb4474e36e4",
            "sourceColumn": "% of Capacity",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Total CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.0000",
            "lineageTag": "ae02181f-e96e-4f8b-903b-0ee0a6923b6d",
            "sourceColumn": "Total CU (s)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Timepoint CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.0000",
            "lineageTag": "84a34963-8f8a-4780-a6fa-104b72b0f3c5",
            "sourceColumn": "Timepoint CU (s)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Capacity CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7d50ee7a-1b61-4b38-8bda-a0ea04aec408",
            "sourceColumn": "Capacity CU (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Base Capacity CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6afd4222-0d96-46b4-9c88-6beaa92c59bc",
            "sourceColumn": "Base Capacity CU (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "% of Base Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "30f01916-83ff-4a74-b3fb-247865fa3f47",
            "sourceColumn": "% of Base Capacity",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Billing type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f370bf12-9464-4ce3-9e5a-619c098f68e7",
            "sourceColumn": "Billing type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CapacityActivationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33c43a4a-a50f-4fda-9901-56d334f1a522",
            "sourceColumn": "CapacityActivationId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "486147ec-c5dd-411a-98e0-d018c561576b",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c9e4b03-25f3-4e8b-afff-e05eab4f99b7",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3c78d826-8f5d-489c-ba32-63709849f7e9",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6f4780b9-e6c6-46d7-80aa-89abe9cbfff4",
        "partitions": [
          {
            "name": "TimePoint2InteractiveDetail-17153823-6433-45c1-9994-0886765dedb7",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Timepoint",
            "source": {
              "expression": [
                "let",
                "  Source = fnGetData(\"TimePointInteractiveDetailForTridentV4\", null, TimePoint2, \"14\"),",
                "  #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Artifact\", \"Item\"}})",
                "in ",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePoint2BackgroundDetail",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OperationStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "96140a88-d71b-4eeb-95a2-e8f0951a4040",
            "sourceColumn": "OperationStartTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "OperationEndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "566926d0-0252-4799-a7b8-6e1057ef2d54",
            "sourceColumn": "OperationEndTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9efc263a-fd1f-489f-a5f9-5d953d248f77",
            "sourceColumn": "Status",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9ccec5d-1158-456a-8a10-27de4683f39b",
            "sourceColumn": "Item",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "243e7e4b-fbfb-496a-a001-25fc5057f7f5",
            "sourceColumn": "Operation",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "OperationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1c58c8e-4612-4b67-986b-c34927cae30a",
            "sourceColumn": "OperationId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80b8c373-571d-4645-83e3-2ce8e54c2d6a",
            "sourceColumn": "User",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "481a69ab-2281-42da-864f-f9292eedec16",
            "sourceColumn": "Start",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "End",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "258406cb-6473-4718-91f0-e98181d99e12",
            "sourceColumn": "End",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Duration (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "6fd77203-3e00-436c-b715-394d78ddbdf4",
            "sourceColumn": "Duration (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Throttling (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "c0dfddfd-a2e6-4b9a-a091-f765268c2b47",
            "sourceColumn": "Throttling (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "% of Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "151e4b91-901f-44cf-afc8-22700ab0357e",
            "sourceColumn": "% of Capacity",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Total CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.0000",
            "lineageTag": "9cd144ec-9e94-4cd1-b6be-00b8d194ad3d",
            "sourceColumn": "Total CU (s)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Timepoint CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.0000",
            "lineageTag": "4e62ca36-f2c8-4f4a-96ed-198b6ad6cddb",
            "sourceColumn": "Timepoint CU (s)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Capacity CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9bb01c84-3d9c-4717-b829-3bd27b7dd7a6",
            "sourceColumn": "Capacity CU (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Base Capacity CU (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e7597ae-2164-4980-85c3-0490167cc41f",
            "sourceColumn": "Base Capacity CU (s)",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "% of Base Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "75d03b77-2410-41d4-b53c-afbbb4f2a7f8",
            "sourceColumn": "% of Base Capacity",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Billing type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70b5a879-133b-441c-a5db-8097fb63e234",
            "sourceColumn": "Billing type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CapacityActivationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43f10958-f526-4c69-9e08-0469310db465",
            "sourceColumn": "CapacityActivationId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2530579a-c59b-4cfb-8c1a-00f32418f5a1",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "855a74e0-51f0-4ac4-a4d0-380cd03832df",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5a61aa3f-be73-4ba8-99e6-0cb8f283645f",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "59916807-3069-410d-b42a-c23bbf1ba3e4",
        "partitions": [
          {
            "name": "TimePoint2BackgroundDetail-a5519e23-cd3a-41a9-9ca4-9f7f6080108c",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Timepoint",
            "source": {
              "expression": [
                "let",
                "  Source = fnGetData(\"TimePointBackgroundDetailForTridentV3\", null, TimePoint2,\"14\"),",
                "#\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Artifact\", \"Item\"}})",
                "in ",
                "#\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MetricsByItemandOperationandDay",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9a7a0e63-488a-4352-9b83-904a78ead322",
            "sourceColumn": "DateTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "76491d14-b03d-4e7b-b064-9ee19eae8183",
            "sourceColumn": "Date",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "337df69c-6529-4ccb-a653-aba2e974c2a6",
            "sourceColumn": "ItemId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "OperationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7404e8b-1ec3-4b93-ae21-01ac41acb4dc",
            "sourceColumn": "OperationName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sum_CU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.000",
            "isNullable": false,
            "lineageTag": "8bfa0324-1dce-45ef-a468-809298dedd9e",
            "sourceColumn": "sum_CU",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "sum_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.000",
            "isNullable": false,
            "lineageTag": "100416f3-fb3a-4a69-9cf5-720f7e9b69ec",
            "sourceColumn": "sum_duration",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1462a917-4345-443b-babd-85aa54a8e08a",
            "sourceColumn": "count_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_users",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "62d40892-1600-4dfc-9078-6a97a49bf908",
            "sourceColumn": "count_users",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_50",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "f7e49d54-823d-464e-8703-0a5989070c18",
            "sourceColumn": "percentile_DurationMs_50",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_90",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "f14df64e-d0ba-41e9-888e-23d774e6a94c",
            "sourceColumn": "percentile_DurationMs_90",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "avg_DurationMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "935f8714-7f7c-4d1a-97f8-9709319e5636",
            "sourceColumn": "avg_DurationMS",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e10d2bf-f5d4-46d9-82ef-ede73b302845",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Throttling (min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9a94e07d-9cd8-4ffa-950b-91ea8f44839b",
            "sourceColumn": "Throttling (min)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_failure_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a26e53f-c4b1-45a6-b24a-16663a7edcc7",
            "sourceColumn": "count_failure_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_rejected_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2d75032-690d-4fff-b1fc-db9d1f8ec474",
            "sourceColumn": "count_rejected_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_successful_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7b5c725a-954b-4803-a5bd-e35672055f74",
            "sourceColumn": "count_successful_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_InProgress_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cbc0cc57-8391-4c91-b88d-7e8be21823f1",
            "sourceColumn": "count_InProgress_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_cancelled_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e98ada6e-1dbb-454c-b228-580f53f773fa",
            "sourceColumn": "count_cancelled_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "count_Invalid_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "31af8604-3883-44af-a109-574878d8327b",
            "sourceColumn": "count_Invalid_operations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fcb9d22-b788-43e4-a707-5367272fc3b5",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3ce7b0ae-68e0-450d-8ef9-eec770d53e7a",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "df3a756b-19e5-4ea7-b9b2-a6f0367934e9",
        "partitions": [
          {
            "name": "MetricsByItemandOperationandDay-1a11e85a-8179-4800-afea-2eef3112934b",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Metrics Preview",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"MetricsByArtifactsAndOperationAndDayForTridentV2\"),",
                "    #\"Uppercased Text\" = Table.TransformColumns(Source,{{\"ArtifactId\", Text.Upper, type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Uppercased Text\",{{\"sum_cpu\", \"sum_CU\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"sum_CU\", type number}, {\"sum_duration\", type number}}),",
                "    #\"Divided Column\" = Table.TransformColumns(#\"Changed Type\", {{\"sum_CU\", each _ / 1000, Double.Type }}),",
                "    #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"sum_duration\", each _ / 1000, Double.Type }}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Divided Column1\",{{\"ArtifactId\", \"ItemId\"}})",
                "in ",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MaxMemoryByItem",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "3fdf621c-00c7-4e1e-b251-7860b26736c0",
            "sourceColumn": "ItemId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Item Size (GB)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "afdaa737-5ee0-41c6-bc78-4456bf410a10",
            "sourceColumn": "Item Size (GB)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "SkuMemory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08b4be4e-a6e9-4161-b66c-65ac076c4c5a",
            "sourceColumn": "SkuMemory",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce71b4f5-c671-42f7-9e3e-cd0432928ac0",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "ItemKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae55d070-49b7-4575-882c-35c880766b32",
            "sourceColumn": "ItemKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9a99c635-99dd-47fd-9df9-9c8962bf0c92",
        "partitions": [
          {
            "name": "MaxMemoryByItem-b47a2b85-bb1a-4cff-b64c-d0bd380e2d7a",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Performance",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"MaxMemoryByArtifactV2\"),",
                "    #\"Uppercased Text\" = Table.TransformColumns(Source,{{\"ArtifactId\", Text.Upper, type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Uppercased Text\",{{\"ArtifactId\", \"ItemId\"}, {\"Artifact Size (GB)\", \"Item Size (GB)\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"ItemKey\", each [PremiumCapacityId]&[ItemId])",
                "in ",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MetricsByItem",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "ac048652-93c3-4fc2-a1f9-20e0c21fade3",
            "sourceColumn": "ItemId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "ArtifactKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e726a352-e516-4585-8c41-514590306099",
            "sourceColumn": "ArtifactKind",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sum_CU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "79ea8277-084a-4643-9d64-8260ad9e7ddf",
            "sourceColumn": "sum_CU",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "sum_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "a169b440-3882-4f7a-aad2-74d8eb012325",
            "sourceColumn": "sum_duration",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_users",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f099742-39cb-44bd-b731-31753dcb7afd",
            "sourceColumn": "count_users",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_50",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e0e8f32c-1b98-4660-9f4a-d422ae838a79",
            "sourceColumn": "percentile_DurationMs_50",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_90",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e966e967-9e3f-4e8f-8427-77a25bffa82a",
            "sourceColumn": "percentile_DurationMs_90",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "avg_DurationMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f8d813f-dc96-4f55-9feb-238c19da7941",
            "sourceColumn": "avg_DurationMs",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adc1998c-de12-4ab5-8ce9-75fe374925b8",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "count_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59a45081-431b-4b15-b601-c7c8aa8aea3c",
            "sourceColumn": "count_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "emptyOperationIdCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "915fe4bb-c697-4362-8a72-6289a874e62c",
            "sourceColumn": "emptyOperationIdCount",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "validOperationIdCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c23f64c9-5118-4804-9447-649d79753765",
            "sourceColumn": "validOperationIdCount",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Billing type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e743a912-20fd-4203-ab25-57e69ee1973e",
            "sourceColumn": "Billing type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Throttling (min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f9f5153c-0227-4a50-be1a-21f3c0d5174d",
            "sourceColumn": "Throttling (min)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_rejected_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08cc3484-5b15-493a-8379-9796df29641c",
            "sourceColumn": "count_rejected_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_successful_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78a72e72-3df3-4c54-a1f5-0ea044c78e79",
            "sourceColumn": "count_successful_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_failure_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f2491653-e9df-413e-aedd-474c1df944bf",
            "sourceColumn": "count_failure_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_InProgress_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "06a8b6be-6342-49aa-89c8-dceab1dea389",
            "sourceColumn": "count_InProgress_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_cancelled_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c506884-4a69-4ac8-b63e-333f771711a5",
            "sourceColumn": "count_cancelled_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_Invalid_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "96f9cdd0-c770-477d-abb0-ac2ad2e5238a",
            "sourceColumn": "count_Invalid_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b7de33d-5fe2-4692-9dad-4cdbf25471c6",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "931a0a08-d398-40d8-b97e-0e724d9ce899",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1acefdd2-bfd5-45b3-8c01-f10ce770846d",
        "partitions": [
          {
            "name": "MetricsByItem-2f4efe08-fe1d-47f8-97fd-dc32436d84ee",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Metrics Preview",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"MetricsByArtifactsForTrident\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"sum_cpu\", Double.Type}, {\"sum_duration\", Double.Type}, {\"count_operations\", Int64.Type}, {\"count_users\", Int64.Type}, {\"percentile_DurationMs_50\", Int64.Type}, {\"percentile_DurationMs_90\", Int64.Type}, {\"avg_DurationMs\", Int64.Type}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Changed Type\",{{\"ArtifactId\", Text.Upper, type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Uppercased Text\",{{\"ArtifactId\", \"ItemId\"}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Renamed Columns1\",{{\"sum_cpu\", \"sum_CU\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"sum_CU\",  Double.Type}, {\"sum_duration\",  Double.Type}}),",
                "    #\"Divided Column\" = Table.TransformColumns(#\"Changed Type1\", {{\"sum_CU\", each _ / 1000,  Double.Type}}),",
                "    #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"sum_duration\", each _ / 1000,  Double.Type}})",
                "in",
                "    #\"Divided Column1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "OperationNames",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "OperationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cab90be0-b0db-470b-8df8-b4377e654ecf",
            "sourceColumn": "OperationName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a89e2afd-a3fc-4378-b2f4-cd0b7181bc48",
        "partitions": [
          {
            "name": "OperationNames-bb456675-54cf-4b1b-b8a7-d9ff907ff0c2",
            "mode": "import",
            "queryGroup": "Capacity",
            "source": {
              "expression": [
                "let ",
                "   Source = try fnGetData(\"GetCapacitiesForTrident\"),",
                "    ValidateNoErros =",
                "        if not (Source[HasError]) then",
                "            Source[Value]",
                "        else if Text.Contains(Source[Error][Message], \"The column 'Column1' of the table wasn't found.\") then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            error Source[Error][Message],",
                "    SourceWithNull =",
                "        if List.IsEmpty(ValidateNoErros[capacityId]) then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            ValidateNoErros,",
                "   ",
                "#\"Removed Other Columns\" = Table.SelectColumns(SourceWithNull,{\"capacityId\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Other Columns\", \"myCustomFunction\",  each fnGetData(\"OperationNamesForTrident\",[capacityId])),",
                "    #\"Expanded myCustomFunction\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"myCustomFunction\", {\"OperationName\"}, {\"OperationName\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Expanded myCustomFunction\", {\"OperationName\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Duplicates\",{\"capacityId\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([OperationName] <> null and [OperationName] <> \"\"))",
                "in   ",
                "#\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dynamic Columns",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a8d436d1015741db8eb16533bd45a43b"
          }
        ],
        "columns": [
          {
            "name": "Dynamic Columns",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "bdf13dd9-732d-4934-ae81-27acfbf2031c",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Dynamic Columns Fields"
                }
              ]
            },
            "sortByColumn": "Dynamic Columns Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dynamic Columns Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "d7c6e7a8-da03-4ae2-95f9-88af74440987",
            "sortByColumn": "Dynamic Columns Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dynamic Columns Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "277e90cc-653b-403c-95a6-943932929d66",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "47df30dd-2aaf-482b-8a56-a445f927096d",
        "partitions": [
          {
            "name": "Dynamic Columns-7fe90f68-8afa-45f0-8cb4-a7b5b7a6496d",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "\t(\"Rejected count\", NAMEOF('All Measures'[Dynamic M1 Rejected Op Count]), 0),",
                "\t(\"Failed count\", NAMEOF('All Measures'[Dynamic M1 Failed Op Count]), 1),",
                "\t(\"Invalid count\", NAMEOF('All Measures'[Dynamic M1 Invalid Op Count]), 2),",
                "\t(\"InProgress count\", NAMEOF('All Measures'[Dynamic M1 InProgress Op Count]), 3),",
                "\t(\"Successful count\", NAMEOF('All Measures'[Dynamic M1 Successful Op Count]), 4),",
                "    (\"Virtualized item\", NAMEOF(Items[IsVirtualArtifactName]), 5),",
                "\t(\"Virtualized workspace\", NAMEOF(Items[IsVirtualWorkspaceName]), 6),",
                "\t(\"Item size (GB)\", NAMEOF('All Measures'[Dynamic M1 Memory Preview]), 7),",
                "    (\"Overloaded minutes\", NAMEOF('All Measures'[Dynamic M1 Throttling (min)]), 8),",
                "    (\"Performance delta\", NAMEOF('All Measures'[Dynamic M1 Perf Preview]), 9)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "MetricsByItemandOperation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "OperationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f4bbc4e-7191-48af-84da-d3b0e0543883",
            "sourceColumn": "OperationName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "5c7c8538-ae3a-4811-bd55-8332185c21f9",
            "sourceColumn": "ItemId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "ArtifactKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa357ca4-0de5-413c-b789-c7b98b2d5e96",
            "sourceColumn": "ArtifactKind",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "sum_CU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "be01c695-82e9-4515-9220-c0cf9ebde224",
            "sourceColumn": "sum_CU",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "sum_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "3e3e9baa-bc84-4442-880d-f971fbf73b20",
            "sourceColumn": "sum_duration",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_users",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0301446d-b8ed-4cc1-acb3-df9bd72c32dc",
            "sourceColumn": "count_users",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_50",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08e1cf34-0620-418f-a7e4-b0845267e975",
            "sourceColumn": "percentile_DurationMs_50",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "percentile_DurationMs_90",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "01873d92-b1ad-4975-a262-9ec2ca2c9a71",
            "sourceColumn": "percentile_DurationMs_90",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "avg_DurationMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b4c72e1b-1e64-45cc-b135-c91df32fc678",
            "sourceColumn": "avg_DurationMs",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c09d8a2a-af94-421f-b4b5-9357f980c2ff",
            "sourceColumn": "count_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad6e647b-cb8c-4d44-851b-4729c82ffdb0",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emptyOperationIdCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c211506-a51f-4768-88fe-5eee48ff6df1",
            "sourceColumn": "emptyOperationIdCount",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "validOperationIdCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7d84b66b-c7c0-4775-856c-627d35362aa4",
            "sourceColumn": "validOperationIdCount",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "Billing type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76730717-8652-4681-819b-2fe465a00c46",
            "sourceColumn": "Billing type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Throttling (min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4f6a3a2b-d701-41b7-bb0e-2ba68b249d53",
            "sourceColumn": "Throttling (min)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "count_rejected_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15526952-93a2-459e-b74c-7d5b5b23a841",
            "sourceColumn": "count_rejected_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_successful_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bf4eb4f2-5f60-43c6-874b-bfea41d91acc",
            "sourceColumn": "count_successful_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_failure_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f4748db8-f466-43c0-a962-f22e93a3d8a4",
            "sourceColumn": "count_failure_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_InProgress_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f5758e5c-5ec8-4923-899e-522be0138340",
            "sourceColumn": "count_InProgress_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_cancelled_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72d89735-d052-4c5a-82f3-6682d1fd08c8",
            "sourceColumn": "count_cancelled_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "count_Invalid_operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "859b0233-282a-4b7d-a6a0-b388b05e1f96",
            "sourceColumn": "count_Invalid_operations",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eff73526-3ac6-41ce-8240-5d2ffadc6116",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UniqueKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a00d7476-0a81-4473-a0ca-710eaab5bf9b",
            "sourceColumn": "UniqueKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "56f8c7b0-0dd8-473f-a4da-107a2fa8d2a0",
        "partitions": [
          {
            "name": "MetricsByItemandOperation-cd4b39cd-f681-49f3-8156-c929427a0b93",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Metrics Preview",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"MetricsByArtifactAndOperationForTrident\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"sum_cpu\",  Double.Type}, {\"sum_duration\",  Double.Type}, {\"count_operations\", Int64.Type}, {\"count_users\", Int64.Type}, {\"percentile_DurationMs_50\", Int64.Type}, {\"percentile_DurationMs_90\", Int64.Type}, {\"avg_DurationMs\", Int64.Type}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Changed Type\",{{\"ArtifactId\", Text.Upper, type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Uppercased Text\",{{\"ArtifactId\", \"ItemId\"}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Renamed Columns1\",{{\"sum_cpu\", \"sum_CU\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"sum_CU\", Double.Type}, {\"sum_duration\", Double.Type}}),",
                "    #\"Divided Column\" = Table.TransformColumns(#\"Changed Type1\", {{\"sum_CU\", each _ / 1000, Double.Type}}),",
                "    #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"sum_duration\", each _ / 1000, Double.Type}})",
                "in",
                "    #\"Divided Column1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ItemKind",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ItemKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f973f345-f6ba-4c04-a5e7-f945c6aa5dde",
            "sourceColumn": "ItemKind",
            "summarizeBy": "none"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a92e0cc-3810-4bbc-b969-81cd443c14a2",
            "sourceColumn": "Measure",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b3526854-4681-408c-af72-996277752916",
        "partitions": [
          {
            "name": "ItemKind-b087f4df-7046-403e-acc6-02c5070a00ba",
            "mode": "import",
            "queryGroup": "Capacity",
            "source": {
              "expression": [
                "let ",
                "   Source = try fnGetData(\"GetCapacitiesForTrident\"),",
                "    ValidateNoErros =",
                "        if not (Source[HasError]) then",
                "            Source[Value]",
                "        else if Text.Contains(Source[Error][Message], \"The column 'Column1' of the table wasn't found.\") then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            error Source[Error][Message],",
                "    SourceWithNull =",
                "        if List.IsEmpty(ValidateNoErros[capacityId]) then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            ValidateNoErros,",
                "   ",
                "#\"Removed Other Columns\" = Table.SelectColumns(SourceWithNull,{\"capacityId\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Other Columns\", \"myCustomFunction\",  each fnGetData(\"ArtifactsV2ForTrident\",[capacityId])),",
                "    #\"Expanded myCustomFunction\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"myCustomFunction\", {\"ArtifactKind\"}, {\"ArtifactKind\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Expanded myCustomFunction\",{\"ArtifactKind\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns1\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Duplicates\", \"Measure\", each if [ArtifactKind] = \"Dataset\" then \"Item Size (GB),Overloaded minutes,Performance delta,Rejected count,Failed count,Invalid count,InProgress count,Successful count,Virtualized item,Virtualized workspace\" else \"Overloaded minutes,Performance delta,Rejected count,Failed count,Invalid count,InProgress count,Successful count,Virtualized item,Virtualized workspace\"),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Added Conditional Column\", \"Measure\", Splitter.SplitTextByDelimiter(\",\", QuoteStyle.None), {\"Measure.1\", \"Measure.2\", \"Measure.3\",\"Measure.4\", \"Measure.5\", \"Measure.6\", \"Measure.7\",\"Measure.8\",\"Measure.9\",\"Measure.10\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"Measure.1\", type text}, {\"Measure.2\", type text}, {\"Measure.3\", type text},{\"Measure.4\", type text}, {\"Measure.5\", type text}, {\"Measure.6\", type text},{\"Measure.7\", type text},{\"Measure.8\", type text},{\"Measure.9\", type text},{\"Measure.10\", type text}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"ArtifactKind\"}, \"Attribute\", \"Value\"),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Unpivoted Other Columns\",{\"Attribute\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"ArtifactKind\", \"ItemKind\"}, {\"Value\", \"Measure\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each ([ItemKind] <> null))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "StorageByWorkspaces",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e19f5d6-6711-4172-a2ec-13d9b6f91401",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Utilization (GB)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f32cf467-e636-4b16-8b20-edc6262fe686",
            "sourceColumn": "Utilization (GB)",
            "sourceProviderType": "decimal",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d3a3da5-458c-4a08-9a69-8cb2ee77e394",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81a06095-f3c7-42ed-90fb-de7c06cf0407",
            "sourceColumn": "WorkspaceKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "StaticStorageInGb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "80f0c9b4-7f43-4896-ba96-e810119ae40d",
            "sourceColumn": "StaticStorageInGb",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "70c73c63-3070-4748-a77a-eb00d9d85320",
        "partitions": [
          {
            "name": "StorageByWorkspaces-5579900b-05f3-4592-bc23-476e3bea1fa0",
            "mode": "directQuery",
            "queryGroup": "Onelake",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"StorageByWorkspaces\",null,null,\"30\")",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "StorageByWorkspacesandDay",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c48242d7-3226-49a1-93b4-a657899ed851",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Utilization (GB)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8832f4a1-c305-4afc-bb96-ef5b32a536c2",
            "sourceColumn": "Utilization (GB)",
            "sourceProviderType": "decimal",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0740cf93-2925-4543-b1c6-e360fd32d260",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f8bdd7ae-4285-4d5e-8bef-7cc25f7d9ef3",
            "sourceColumn": "Date",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35ac77fd-b9c3-4eae-a614-5e7a6c2c9efc",
            "sourceColumn": "WorkspaceKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c145e53a-5e57-40b8-8f88-5da00f05b0e7",
            "sourceColumn": "Hours",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "StaticStorageInGb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fab03c63-6338-4108-9e1e-d668be0f0818",
            "sourceColumn": "StaticStorageInGb",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "OperationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9aff2c1a-d276-43b2-911b-860607103e72",
            "sourceColumn": "OperationName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "WorkloadKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5c0ad8e-b863-4125-bb0f-a76acce1cca8",
            "sourceColumn": "WorkloadKind",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Billing type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78d0a397-16b7-4540-8627-df6c4e507ccb",
            "sourceColumn": "Billing type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "WorkloadOperationKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e19a6384-1124-45e1-b3e4-103bb3310663",
            "sourceColumn": "WorkloadOperationKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c1aaae37-1f22-4858-b2b1-1056e8e50d37",
        "partitions": [
          {
            "name": "StorageByWorkspacesandDay-3765b2ea-3d48-41f3-9418-0abc8f30674c",
            "mode": "directQuery",
            "queryGroup": "Onelake",
            "source": {
              "expression": [
                "let",
                "",
                "    Source = fnGetData(\"StorageByWorkspacesAndDayV2\",null,null,\"30\")",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "StorageByWorkspacesandHour",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90f69816-03ae-4512-833a-8378aaad7411",
            "sourceColumn": "WorkspaceId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Utilization (GB)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aef6a17f-803b-4733-8388-40f749cac363",
            "sourceColumn": "Utilization (GB)",
            "sourceProviderType": "decimal",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57c7839b-f2d6-4b2b-9400-54af35e36d35",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a96e2c59-392b-4b7d-a8fe-f3b1451e512b",
            "sourceColumn": "DateTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b14b1fcc-91df-4e48-9705-ed568b096f9b",
            "sourceColumn": "WorkspaceKey",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6f72adb6-7543-429c-ba70-28758a7ee932",
            "sourceColumn": "Date",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "StaticStorageInGb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6bdbc888-985a-451d-8fd0-706007dec3e9",
            "sourceColumn": "StaticStorageInGb",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "OperationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ec18208-2683-4b00-ba8d-7a755fe7480e",
            "sourceColumn": "OperationName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "WorkloadKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9611153-e8a1-4ab0-9088-107751a81a7a",
            "sourceColumn": "WorkloadKind",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Billing type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "426c7578-156e-4a0a-856c-a5f58209938f",
            "sourceColumn": "Billing type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "StorageType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dabcef4b-aea8-41e6-bcd3-7ae82abbfb92",
            "sourceColumn": "StorageType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "94ef68b3-fb80-48dd-a518-4836733ccb68",
        "partitions": [
          {
            "name": "StorageByWorkspacesandHour-ca5ffe68-20f2-4094-976d-8b7199c210c9",
            "mode": "directQuery",
            "queryGroup": "Onelake",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"StorageByWorkspacesAndHourV2\",null,null,\"30\"),",
                "    Custom1 = Table.AddColumn(Source, \"StorageType\", each",
                "        if [OperationName] = \"KustoStandardStorage\" then \"OneLake Standard Storage\"",
                "        else if [OperationName] = \"KustoCacheStorage\" then \"OneLake Premium Storage\"",
                "        else if [OperationName] = \"OneLake Storage\" then \"OneLake Standard Storage\"",
                "        else if [OperationName] = \"OneLake BCDR Storage\" then \"BCDR Storage\"",
                "        else \"Unspecified\"",
                "    )",
                "in",
                "    Custom1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Top N Selector",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1511c65e62bd476ab1471525b4e3a3f0"
          }
        ],
        "columns": [
          {
            "name": "Top N",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d44a1429-4d01-4157-b7b6-5740338f6745",
            "sourceColumn": "[Top N]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "884cbd40-dc25-4a9f-9f8c-698564f1fbf4",
        "partitions": [
          {
            "name": "Top N Selector-0022cd1f-0c23-4117-8afd-6f133c667241",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"Top N\",",
                "        INTEGER,    {",
                "        { 10 },",
                "        { 100 },",
                "        {1000},",
                "        {10000}",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Workspaces",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a63e5b3e-e841-4f15-9750-8b3ba5359219",
            "sourceColumn": "WorkspaceId",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fd1202a-8dbc-4c8f-9e43-b35e35098f62",
            "sourceColumn": "WorkspaceKey",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ba34bdc-85e8-4dbb-9248-bd4230c4bb10",
            "sourceColumn": "WorkspaceName",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "722afddd-dbef-440a-b94d-896edcdb0781",
            "sourceColumn": "PremiumCapacityId",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceProvisionState",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40f26adc-58e4-4124-8f89-19b2d010a99b",
            "sourceColumn": "WorkspaceProvisionState",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "89fe97cf-8d35-404e-9804-8c5a9de3a0db",
        "partitions": [
          {
            "name": "Workspaces-b19860df-9aa7-46de-8cd6-b6019ab6f289",
            "mode": "import",
            "queryGroup": "Capacity",
            "source": {
              "expression": [
                "let ",
                "   Source = try fnGetData(\"GetCapacitiesForTrident\"),",
                "    ValidateNoErros =",
                "        if not (Source[HasError]) then",
                "            Source[Value]",
                "        else if Text.Contains(Source[Error][Message], \"The column 'Column1' of the table wasn't found.\") then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            error Source[Error][Message],",
                "    SourceWithNull =",
                "        if List.IsEmpty(ValidateNoErros[capacityId]) then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            ValidateNoErros,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(SourceWithNull,{\"capacityId\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Other Columns\", \"myCustomFunction\",  each fnGetData(\"WorkspacesForStorage\",[capacityId],null,\"30\")),",
                "    #\"Expanded myCustomFunction\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"myCustomFunction\", {\"WorkspaceId\", \"WorkspaceName\", \"WorkspaceProvisionState\"}, {\"WorkspaceId\", \"WorkspaceName\", \"WorkspaceProvisionState\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Expanded myCustomFunction\", \"WorkspaceKey\", each [capacityId] & [WorkspaceId]),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Added Custom\", {\"WorkspaceKey\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"capacityId\", \"PremiumCapacityId\"}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Renamed Columns\", each ([WorkspaceKey] <> \"\" and [WorkspaceKey] <> null))",
                "in",
                "    #\"Filtered Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CUDetail",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "WindowStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a9d97aff-db11-46c5-968d-69f37c3e98f6",
            "sourceColumn": "WindowStartTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Interactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "isNullable": false,
            "lineageTag": "68eaa3db-0eae-47be-a9c2-738b3e91598b",
            "sourceColumn": "Interactive",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "Background",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "isNullable": false,
            "lineageTag": "0b59b8da-7308-4115-a155-2f61c7df4093",
            "sourceColumn": "Background",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "InteractivePreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "isNullable": false,
            "lineageTag": "e01b9636-0d27-4428-98b0-88d7bfbd849b",
            "sourceColumn": "InteractivePreview",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "BackgroundPreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "isNullable": false,
            "lineageTag": "71302081-b69e-4fac-b9d2-2f0e4964646c",
            "sourceColumn": "BackgroundPreview",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "Interactive Delay %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "7e85bf6b-2e88-4daa-9b7b-ebe974ed48cd",
            "sourceColumn": "Interactive Delay %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Interactive Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "8ae12396-37c1-4adc-a213-65cb56b509ee",
            "sourceColumn": "Interactive Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Background Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "6d08ac61-ed6d-47a5-8b77-a40050767e2c",
            "sourceColumn": "Background Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "AutoScaleCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21d6c855-4465-424f-9f07-0d772597709a",
            "sourceColumn": "AutoScaleCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "StartOfHour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e4458a08-7bd4-4ab9-adc2-b89bf7a92e6a",
            "sourceColumn": "StartOfHour",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "CUs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "788d2318-67b4-4434-a844-10383b07ce5f",
            "sourceColumn": "CUs",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "609da27b-dea1-4c06-b888-ce58f20204d1",
            "sourceColumn": "BaseCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "WindowEndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ae19d8e0-4c0f-4123-8214-3a911c37d453",
            "sourceColumn": "WindowEndTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Threshold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9ddfaf24-c0f8-4081-9aa4-b3754d4769fd",
            "sourceColumn": "Threshold",
            "summarizeBy": "none"
          },
          {
            "name": "StartOf6min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ffe52ea0-b9c7-4d3e-9ca8-c73a04d028bf",
            "sourceColumn": "StartOf6min",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Peak6minInteractive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "42fa1ebb-2555-4bf5-9722-d9c5a1767e1b",
            "sourceColumn": "Peak6minInteractive",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Peak6minBackground",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7da03b36-8145-45ce-a8f8-f9e2fc15a9ad",
            "sourceColumn": "Peak6minBackground",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Peak6minInteractivePreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "13ccd18e-de4b-4a65-a108-ad5d452caa74",
            "sourceColumn": "Peak6minInteractivePreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Peak6minBackgroundPreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cb701ada-5ebc-4622-85f7-96d405db205c",
            "sourceColumn": "Peak6minBackgroundPreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Peak6min Interactive Delay %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "f09abee4-b098-442b-99ec-e3c14ec23c12",
            "sourceColumn": "Peak6min Interactive Delay %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Peak6min Interactive Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "d597bc3f-060c-4bf5-94c3-feb4ab891637",
            "sourceColumn": "Peak6min Interactive Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Peak6min Background Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "2646cb98-8d88-4bf5-871c-2efe9e85026e",
            "sourceColumn": "Peak6min Background Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isNullable": false,
            "lineageTag": "21b3a945-f24d-4ddf-a15e-73596275f553",
            "sourceColumn": "Start of Hour",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "CU Limit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7e9ecc7d-e6ef-4bf7-b582-6cedd58e0ee2",
            "sourceColumn": "CU Limit",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "SKU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7b7bfa8-bb1a-4c17-a6f7-85507bc3e427",
            "sourceColumn": "SKU",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "748a0e64-927b-4dfb-aa4f-32e1c62bd061",
        "partitions": [
          {
            "name": "CUDetail",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Timepoint",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"TimePointCUDetailForTridentV4\"),",
                "//     #\"Divided Column\" = Table.TransformColumns(Source, {{\"Interactive Delay %\", each _ / 100.00, type number},{\"Interactive Rejection %\", each _ / 100.00, type number},{\"Background Rejection %\", each _ / 100.00, type number}}),",
                "//     #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"Peak6min Interactive Delay %\", each _ / 100.00, type number},{\"Peak6min Interactive Rejection %\", each _ / 100.00, type number},{\"Peak6min Background Rejection %\", each _ / 100.00, type number}}),",
                "//     #\"Added Custom\" = Table.AddColumn(#\"Divided Column1\", \"Threshold\", each 1)",
                "// in",
                "//     #\"Added Custom\"",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"WindowStartTime\", type datetime}, {\"WindowEndTime\", type datetime}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Changed Type1\",{{\"CpuTimeMs\", Currency.Type}, {\"Interactive\", Currency.Type}, {\"Background\", Currency.Type}}),",
                "    #\"Divided Column\" = Table.TransformColumns(#\"Changed Type\", {{\"CpuTimeMs\", each _ / 1000, Currency.Type}}),",
                "    #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"Interactive\", each _ / 1000, Currency.Type}}),",
                "    #\"Divided Column2\" = Table.TransformColumns(#\"Divided Column1\", {{\"Background\", each _ / 1000, Currency.Type}}),",
                "    #\"Divided Column3\" = Table.TransformColumns(#\"Divided Column2\", {{\"InteractivePreview\", each _ / 1000, Currency.Type}}),",
                "    #\"Divided Column4\" = Table.TransformColumns(#\"Divided Column3\", {{\"BackgroundPreview\", each _ / 1000, Currency.Type}}),",
                "    #\"Inserted Start of Hour\" = Table.AddColumn(#\"Divided Column4\", \"Start of Hour\", each Time.StartOfHour([WindowStartTime]), type datetimezone),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Inserted Start of Hour\",0,null,Replacer.ReplaceValue,{\"Peak6minInteractive\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",0,null,Replacer.ReplaceValue,{\"Peak6minBackground\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",0,null,Replacer.ReplaceValue,{\"Peak6minInteractivePreview\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",0,null,Replacer.ReplaceValue,{\"Peak6minBackgroundPreview\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Replaced Value3\",{{\"CpuTimeMs\", \"CUs\"}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Renamed Columns1\", \"CU Limit\", each 1),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"CU Limit\", type number}}),",
                "    #\"Divided Column5\" = Table.TransformColumns(#\"Changed Type2\", {{\"Interactive Delay %\", each _ / 100.00, type number},{\"Interactive Rejection %\", each _ / 100.00, type number},{\"Background Rejection %\", each _ / 100.00, type number}}),",
                "    #\"Divided Column6\" = Table.TransformColumns(#\"Divided Column5\", {{\"Peak6min Interactive Delay %\", each _ / 100.00, type number},{\"Peak6min Interactive Rejection %\", each _ / 100.00, type number},{\"Peak6min Background Rejection %\", each _ / 100.00, type number}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Divided Column6\", \"Threshold\", each 1),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Added Custom\",0,null,Replacer.ReplaceValue,{\"Peak6min Interactive Delay %\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",0,null,Replacer.ReplaceValue,{\"Peak6min Interactive Rejection %\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",0,null,Replacer.ReplaceValue,{\"Peak6min Background Rejection %\"})",
                "in",
                "    #\"Replaced Value6\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePointOverageDetail",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WindowStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c874ab9a-651c-469f-bac6-270e0ff4181b",
            "sourceColumn": "WindowStartTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "CumulativeCarryForward",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "c257cb49-edec-402f-88c1-c2fdac41bd3a",
            "sourceColumn": "CumulativeCarryForward",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "CarryForwardAdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "e5e41122-06ec-444d-a3dd-ecf71c4d9b46",
            "sourceColumn": "CarryForwardAdd",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "CarryForwardBurndown",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "7d997ea5-bf8f-4023-81c6-74e535ba8434",
            "sourceColumn": "CarryForwardBurndown",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0e64040-76cc-4c69-980e-d98de8ba7307",
            "sourceColumn": "BaseCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "AutoScaleCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2aedae12-b978-4488-a51f-a1c7dbc414fe",
            "sourceColumn": "AutoScaleCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "StartOf20min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1dc467bc-91b2-4cd6-bbc5-855b8207aa50",
            "sourceColumn": "StartOf20min",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "Peak20minCumulativeCarryForward",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e65f7e20-0c0a-4c73-b46b-458c873570cb",
            "sourceColumn": "Peak20minCumulativeCarryForward",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Peak20minCarryForwardAdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "39ed0bf8-4944-4a9a-a292-a6513fe8d5b6",
            "sourceColumn": "Peak20minCarryForwardAdd",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Peak20minCarryForwardBurndown",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "dbef0bc5-a487-421c-bfb5-c60f9f0e0bae",
            "sourceColumn": "Peak20minCarryForwardBurndown",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "StartOfHour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "46b44e9a-9e95-4ce8-aecb-88754736ff3c",
            "sourceColumn": "StartOfHour",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6f54374b-69a2-4ef9-84c0-04307c2252f7",
        "partitions": [
          {
            "name": "TimePointOverageDetail",
            "mode": "directQuery",
            "queryGroup": "CarryOver",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"TimePointOverageDetailForTridentV3\"),",
                "    #\"Change type\" = Table.TransformColumnTypes(Source,{{\"CumulativeCarryForward\", type number}, {\"CarryForwardAdd\", type number}, {\"CarryForwardBurndown\", type number}}),",
                "    #\"Divide by 1000\" = Table.TransformColumns(#\"Change type\", {{\"CumulativeCarryForward\", each _ / 1000, type number}, {\"CarryForwardAdd\", each _ / 1000, type number}, {\"CarryForwardBurndown\", each _ / 1000, type number}}),",
                "    #\"Multiples by -1\" = Table.TransformColumns(#\"Divide by 1000\", {{\"CarryForwardBurndown\", each _ * -1, type number},{\"Peak20minCarryForwardBurndown\", each _ * -1, type number}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Multiples by -1\",0,null,Replacer.ReplaceValue,{\"Peak20minCumulativeCarryForward\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",0,null,Replacer.ReplaceValue,{\"Peak20minCarryForwardAdd\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",0,null,Replacer.ReplaceValue,{\"Peak20minCarryForwardBurndown\"})",
                "in",
                "    #\"Replaced Value2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePointOveragesByWorkloads",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "WindowStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b3a272ab-dceb-4399-aa3c-ee8800b3b975",
            "sourceColumn": "WindowStartTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "StartOfHour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d07f0b52-6809-47ac-9760-016f2acb9d2b",
            "sourceColumn": "StartOfHour",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "WorkloadKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7896fa1-41c6-41a8-9235-277aa77ea4f8",
            "sourceColumn": "WorkloadKind",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CumulativeCarryForward",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "6d6fc26a-eea7-4207-a2b6-a69b07bc5570",
            "sourceColumn": "CumulativeCarryForward",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "CarryForwardAdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "3b675152-25ca-4e82-9e36-463d2cff28fb",
            "sourceColumn": "CarryForwardAdd",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "CarryForwardBurndown",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "5fb61ca1-4c7c-47f8-a9fb-fa790ea79b07",
            "sourceColumn": "CarryForwardBurndown",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "daba307b-8637-4d33-9949-d4661e4772af",
            "sourceColumn": "BaseCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "AutoScaleCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e0a97a0-d486-4541-8f1c-eb687837b2cb",
            "sourceColumn": "AutoScaleCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f431d3c-d08d-421c-b204-09787f457091",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5f5de3fd-5388-4f86-9240-636ba87fcf64",
        "partitions": [
          {
            "name": "TimePointOveragesByWorkloads",
            "mode": "directQuery",
            "queryGroup": "CarryOver",
            "source": {
              "expression": [
                "let",
                "  Source = fnGetData(\"TimePointOveragesByWorkloadsForTridentV2\", null, TimePoint + #duration(0,0,0,30) ,\"15\"),",
                "    #\"Divided by 1000\" = Table.TransformColumns(Source, {{\"CumulativeCarryForward\", each _ / 1000, type number}, {\"CarryForwardAdd\", each _ / 1000, type number}, {\"CarryForwardBurndown\", each _ /1000, type number} }),",
                "    #\"Multiples by -1\" = Table.TransformColumns(#\"Divided by 1000\", {{\"CarryForwardBurndown\", each _ * -1, type number}})",
                "in",
                "    #\"Multiples by -1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePoint2OveragesByWorkloads",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "WindowStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "dd39e7ab-ee47-4359-b1f5-02fc4d8422f1",
            "sourceColumn": "WindowStartTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "StartOfHour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1992cc26-d17c-445c-8bb8-ad83e16ab617",
            "sourceColumn": "StartOfHour",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "WorkloadKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebed91d2-85d1-4c09-9403-fc95ed9ad119",
            "sourceColumn": "WorkloadKind",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CumulativeCarryForward",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "ee933e6e-2aab-400b-b4ac-a2f28befe14d",
            "sourceColumn": "CumulativeCarryForward",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "CarryForwardAdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "183369ec-64f5-4406-9735-60fc284079a1",
            "sourceColumn": "CarryForwardAdd",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "CarryForwardBurndown",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "5a54b138-829e-4aa8-b16b-e7d7a30efac0",
            "sourceColumn": "CarryForwardBurndown",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "56cc65bf-eaab-438f-bdb4-c6367f8ba634",
            "sourceColumn": "BaseCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "AutoScaleCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c69b944-6aed-47de-964d-c5bc202e388f",
            "sourceColumn": "AutoScaleCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b209015-794c-47b9-b330-2c4356f414dd",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9e5c92ea-a665-48c7-834f-2fdbdca0c26a",
        "partitions": [
          {
            "name": "TimePoint2OveragesByWorkloads",
            "mode": "directQuery",
            "queryGroup": "CarryOver",
            "source": {
              "expression": [
                "let",
                "  Source = fnGetData(\"TimePointOveragesByWorkloadsForTridentV2\", null, TimePoint2 + #duration(0,0,0,30) ,\"15\"),",
                "    #\"Divided by 1000\" = Table.TransformColumns(Source, {{\"CumulativeCarryForward\", each _ / 1000, type number}, {\"CarryForwardAdd\", each _ / 1000, type number}, {\"CarryForwardBurndown\", each _ / 1000, type number} }),",
                "    #\"Multiples by -1\" = Table.TransformColumns(#\"Divided by 1000\", {{\"CarryForwardBurndown\", each _ * -1, type number}})",
                "in",
                "    #\"Multiples by -1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dates",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "ddd d",
            "lineageTag": "ee241133-245b-43c3-bd5f-f10b1d0f78c1",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "string",
            "formatString": "mmm yyyy",
            "lineageTag": "531da88a-fa2d-42c0-bffd-f9861e9efe62",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "First Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "0f202c66-faca-4ff0-a398-89ebceb21e26",
            "sourceColumn": "First Day of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "c1df59ad-a82c-427f-ba38-9576dfaf91f9",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ff19353e-9891-4eee-b7fd-46d2dc9f7bc9",
        "partitions": [
          {
            "name": "Dates",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    startDate = Date.From(Date.AddDays((DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) + #duration(0,0,0,Number.FromText(UTC_offset)*3600)),-30)),",
                "    endDate = Date.From(DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) + #duration(0,0,0,Number.FromText(UTC_offset)*3600)),",
                "    dateList = List.Dates(startDate, Number.From(endDate - startDate) + 1, #duration(1, 0, 0, 0)),",
                "    calendarTable = Table.FromList(dateList, Splitter.SplitByNothing(), {\"Date\"}),",
                "    withStartOfMonth = Table.AddColumn(calendarTable, \"Start of Month\", each Date.From(Date.From([Date]) - Duration.From(Date.Day(Date.From([Date])) - 1))),",
                "    withFirstDayOfWeek = Table.AddColumn(withStartOfMonth, \"First Day of Week\", each [Date] - Duration.From(Date.DayOfWeek([Date], Day.Monday))),",
                "    withDayMonth = Table.AddColumn(withFirstDayOfWeek, \"Day\", each Date.From([Date]))",
                "in",
                "    withDayMonth"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "OperationForStorage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "OperationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "827987c0-009b-4084-960f-dad96b727a77",
            "sourceColumn": "OperationName",
            "summarizeBy": "none"
          },
          {
            "name": "StorageType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "365d622f-c389-4b23-9dea-5c62e33e862c",
            "sourceColumn": "StorageType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "667d251d-a92d-4903-bd18-cb598ba8c4f1",
        "partitions": [
          {
            "name": "OperationForStorage-c7aad02e-ef87-4d44-8bd0-86044d670b5b",
            "mode": "import",
            "queryGroup": "Capacity",
            "source": {
              "expression": [
                "let ",
                "   Source = try fnGetData(\"GetCapacitiesForTrident\"),",
                "    ValidateNoErros =",
                "        if not (Source[HasError]) then",
                "            Source[Value]",
                "        else if Text.Contains(Source[Error][Message], \"The column 'Column1' of the table wasn't found.\") then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            error Source[Error][Message],",
                "    SourceWithNull =",
                "        if List.IsEmpty(ValidateNoErros[capacityId]) then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            ValidateNoErros,",
                "   ",
                "    #\"Removed Other Columns\" = Table.SelectColumns(SourceWithNull,{\"capacityId\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Other Columns\", \"myCustomFunction\",  each  fnGetData(\"WorkloadAndOperationForStorage\",[capacityId],null,\"30\")),",
                "    #\"Expanded myCustomFunction\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"myCustomFunction\", {\"OperationName\"}, {\"OperationName\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Expanded myCustomFunction\", each ([OperationName] <> null and [OperationName] <> \"\")),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Filtered Rows1\", {\"OperationName\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Duplicates\",{\"capacityId\"}),",
                "    Custom1 = Table.AddColumn(#\"Removed Columns\", \"StorageType\", each",
                "        if [OperationName] = \"KustoStandardStorage\" then \"OneLake Standard Storage\"",
                "        else if [OperationName] = \"KustoCacheStorage\" then \"OneLake Premium Storage\"",
                "        else if [OperationName] = \"OneLake Storage\" then \"OneLake Standard Storage\"",
                "        else if [OperationName] = \"OneLake BCDR Storage\" then \"BCDR Storage\"",
                "        else \"Unspecified\"",
                "    )",
                "in",
                "    Custom1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Workloads",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "WorkloadKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45974d51-1518-49c6-b925-3f2ae7fa7c94",
            "sourceColumn": "WorkloadKind",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fc93c290-da52-4f3e-bb69-fa50f291831d",
        "partitions": [
          {
            "name": "Workloads-cd0eb325-3559-498a-8ec5-278b608f869e",
            "mode": "import",
            "queryGroup": "Capacity",
            "source": {
              "expression": [
                "let ",
                "   Source = try fnGetData(\"GetCapacitiesForTrident\"),",
                "    ValidateNoErros =",
                "        if not (Source[HasError]) then",
                "            Source[Value]",
                "        else if Text.Contains(Source[Error][Message], \"The column 'Column1' of the table wasn't found.\") then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            error Source[Error][Message],",
                "    SourceWithNull =",
                "        if List.IsEmpty(ValidateNoErros[capacityId]) then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            ValidateNoErros,",
                "   ",
                "    #\"Removed Other Columns\" = Table.SelectColumns(SourceWithNull,{\"capacityId\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Other Columns\", \"myCustomFunction\",  each  fnGetData(\"WorkloadAndOperationForStorage\",[capacityId],null,\"30\")),",
                "    #\"Expanded myCustomFunction\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"myCustomFunction\", {\"WorkloadKind\"}, {\"WorkloadKind\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Expanded myCustomFunction\", each ([WorkloadKind] <> null and [WorkloadKind] <> \"\")),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Filtered Rows1\", {\"WorkloadKind\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Duplicates\",{\"capacityId\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Billing type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Billing type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96135157-072a-4963-97c1-b9cb55af6b9f",
            "sourceColumn": "Billing type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8df822de-24b8-4891-a85b-9fe98c477f3a",
        "partitions": [
          {
            "name": "Billing type-bc9f9f37-12b7-496d-bc7f-dcc160130fd2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcsrMyUlMyklVitWJVvLLz9NNggvEAgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Billing type\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Billing type\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "WorkloadForStorage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "capacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24488cd9-69c1-4c63-a078-3d1d563a34d9",
            "sourceColumn": "capacityId",
            "summarizeBy": "none"
          },
          {
            "name": "WorkloadKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5d8f653-3afd-4093-8ce2-fe721dd903a2",
            "sourceColumn": "WorkloadKind",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ad6fce1f-6d5c-48b6-b35e-d0f73e663544",
        "partitions": [
          {
            "name": "WorkloadForStorage-ef43c6ef-a929-4e4a-96ea-68a338344b61",
            "mode": "import",
            "queryGroup": "Capacity",
            "source": {
              "expression": [
                "let ",
                "   Source = try fnGetData(\"GetCapacitiesForTrident\"),",
                "    ValidateNoErros =",
                "        if not (Source[HasError]) then",
                "            Source[Value]",
                "        else if Text.Contains(Source[Error][Message], \"The column 'Column1' of the table wasn't found.\") then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            error Source[Error][Message],",
                "    SourceWithNull =",
                "        if List.IsEmpty(ValidateNoErros[capacityId]) then",
                "            error",
                "                \"No capacities found. You need to be a capacity admin of at least one or more capacities.\"",
                "        else",
                "            ValidateNoErros,",
                "   ",
                "    #\"Removed Other Columns\" = Table.SelectColumns(SourceWithNull,{\"capacityId\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Other Columns\", \"myCustomFunction\",  each  fnGetData(\"WorkloadAndOperationForStorage\",[capacityId],null,\"30\")),",
                "    #\"Expanded myCustomFunction\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"myCustomFunction\", {\"WorkloadKind\"}, {\"WorkloadKind\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Expanded myCustomFunction\", each ([WorkloadKind] <> null and [WorkloadKind] <> \"\"))",
                "in",
                "    #\"Filtered Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SystemEvents",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "106513b8-463d-4150-9453-01bbacace5e2",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityState",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89148e54-81ec-4f93-8e44-68da7faf5bde",
            "sourceColumn": "PremiumCapacityState",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityStateChangeReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4116ee3f-7a61-43cb-9255-497b74559da0",
            "sourceColumn": "PremiumCapacityStateChangeReason",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CapacityActivationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86c10dcf-a18b-4d0f-8c7c-3456c030f779",
            "sourceColumn": "CapacityActivationId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CapacityStateTransitionTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "bd2aa7bc-9162-423e-9a39-284f1ed4201b",
            "sourceColumn": "CapacityStateTransitionTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "BinnedCapacityStateTransitionTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0bb51467-e1db-4f9c-8584-02fc5867711f",
            "sourceColumn": "BinnedCapacityStateTransitionTime",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "513c6c82-43ec-43ed-81f9-3b602479edf8",
        "measures": [
          {
            "name": "Pause Resume Cumulative Carry Over Last Window",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE ( SUM ( TimePointOveragesByWorkloads[CumulativeCarryForward] ), TimePointOveragesByWorkloads[WindowStartTime] == (MAX(TimePoints[TimePoint]) - TIME(0,0,30)))"
            ],
            "lineageTag": "ac11c03f-b9e2-414b-98ba-35a95d13db6c"
          },
          {
            "name": "Pause Resume Cumulative Carry Over Last Window %",
            "expression": "[Pause Resume Cumulative Carry Over Last Window]/[Timepoint SKU CU CarryOver]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "290f6f3f-484d-4297-b03d-8d65ffe48d6e"
          },
          {
            "name": "Pause Resume State Change",
            "expression": [
              "",
              "Var x = MAX(SystemEvents[PremiumCapacityState])",
              "Var z = IF(x = \"\", \"No state change\", x)",
              "",
              "return z"
            ],
            "lineageTag": "b7226156-d2d6-4964-a7dd-0d2f2f2d30c0"
          },
          {
            "name": "Pause Resume Cumulative Carry Over Last Window 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE ( SUM ( TimePointOveragesByWorkloads[CumulativeCarryForward] ), TimePointOveragesByWorkloads[WindowStartTime] == (MAX(TimePoints2[TimePoint]) - TIME(0,0,30)))"
            ],
            "lineageTag": "d8c777b6-934f-407f-9d54-0c135e67be54"
          },
          {
            "name": "Pause Resume Cumulative Carry Over Last Window 2 %",
            "expression": "[Pause Resume Cumulative Carry Over Last Window 2]/[Timepoint SKU CU CarryOver T2]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3e97faad-f6ed-4928-b6ce-55952bcde060"
          },
          {
            "name": "Pause Resume State Change 2",
            "expression": [
              "",
              "Var x = MAX(SystemEvents[PremiumCapacityState])",
              "// CALCULATE(",
              "//     MAX(SystemEvents[PremiumCapacityState]), FILTER(SystemEvents,",
              "//     SystemEvents[BinnedCapacityStateTransitionTime] == TimePoints2[End Time 2] - TIME(0,0,30)))",
              "",
              "Var y = IF(x = \"\", \"No state change\", x)",
              "return y"
            ],
            "lineageTag": "ed502cd9-1ce7-412b-9c10-cad75eb96e26"
          },
          {
            "name": "TotalRowCount",
            "expression": "COUNTROWS(SystemEvents)",
            "formatString": "0",
            "lineageTag": "349ba802-1ed3-4480-989b-08f28e11e4c5"
          },
          {
            "name": "StateChangeText",
            "expression": "IF(ISBLANK([TotalRowCount]), \"The state of capacity has remained unchanged in last 14 days.\", \"The capacity state changed \" & [TotalRowCount] & \" times within the last 14 days.\")",
            "lineageTag": "f9e7edd8-1c30-49ef-8f70-765a3d04a766"
          },
          {
            "name": "StateChangeTextStartUpCard",
            "expression": [
              "",
              "VAR x = ISFILTERED(Dates[Date])",
              "VAR y = IF(ISBLANK([TotalRowCount]), \"The state of capacity has remained unchanged in last 14 days.\", \"\")",
              "RETURN ",
              "IF(x && ISBLANK([TotalRowCount]), \"The state of capacity has remained unchanged in selected dates.\",y)"
            ],
            "lineageTag": "6c51ff48-fb5d-4cdf-a5c7-9405c2c1876c"
          },
          {
            "name": "MeasureSystemEvent",
            "expression": "NOT(ISBLANK([TotalRowCount]))",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "715c89ca-704e-4a1f-88bd-03e46f553897"
          }
        ],
        "partitions": [
          {
            "name": "SystemEvents",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Timepoint",
            "source": {
              "expression": [
                "let",
                "",
                "   Source = fnGetData(\"SystemEvents\")",
                "   ",
                "in ",
                "Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimePoint2CUDetail",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "WindowStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9b0df600-491b-4c2c-96d3-5679ef3d5105",
            "sourceColumn": "WindowStartTime",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "WindowEndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c990d243-7e25-4ee1-90ac-b56e6793606b",
            "sourceColumn": "WindowEndTime",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "Interactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"\"\\ #,0.###############;#,0.###############\\ -\"\";\"\"\\ #,0.###############",
            "isNullable": false,
            "lineageTag": "9bd239de-14ec-45bb-937c-6882e913e78e",
            "sourceColumn": "Interactive",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "Background",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"\"\\ #,0.###############;#,0.###############\\ -\"\";\"\"\\ #,0.###############",
            "isNullable": false,
            "lineageTag": "e2ad293b-4d84-406b-93ea-1df2f4bfa9b9",
            "sourceColumn": "Background",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "InteractivePreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "179209ca-1530-418f-ae7b-47a460f8ddb5",
            "sourceColumn": "InteractivePreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "BackgroundPreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "6d400b42-8d3f-4666-8839-1e914943dc29",
            "sourceColumn": "BackgroundPreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Interactive Delay %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "65ac1840-ecce-41ed-b0f0-3ef5d4490101",
            "sourceColumn": "Interactive Delay %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Interactive Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0b3b560-afa9-44fb-8496-5dd891a69c78",
            "sourceColumn": "Interactive Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Background Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c1cfcee2-31fc-42eb-8a6c-87e80743ad44",
            "sourceColumn": "Background Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "AutoScaleCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aeb46e0c-7497-47f4-8f82-500d57ae2699",
            "sourceColumn": "AutoScaleCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "StartOfHour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7b73b4e0-cc1f-46a0-ada9-2f54b46779c3",
            "sourceColumn": "StartOfHour",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          },
          {
            "name": "CUs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"\"\\ #,0.###############;#,0.###############\\ -\"\";\"\"\\ #,0.###############",
            "isNullable": false,
            "lineageTag": "83f8d2f8-40c0-4593-8e31-4c48e119fbf6",
            "sourceColumn": "CUs",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseCapacityUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7e6d3028-e2e5-41ea-b394-b45184aebb14",
            "sourceColumn": "BaseCapacityUnits",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "CU Limit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9291b492-aac8-4c34-b7d1-9ad84a2a36a8",
            "sourceColumn": "CU Limit",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHourInteractive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "25c2490a-90e3-48c5-967d-c50bb370b943",
            "sourceColumn": "PeakHourInteractive",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHourBackground",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b57dac0e-8fa5-44dd-8920-64ab59db4a3f",
            "sourceColumn": "PeakHourBackground",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHourInteractivePreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3b596b90-1fed-4110-99f6-87929b7d67cc",
            "sourceColumn": "PeakHourInteractivePreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHourBackgroundPreview",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "df261961-23df-4b4a-ab6d-db886db49edb",
            "sourceColumn": "PeakHourBackgroundPreview",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHour Interactive Delay %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3d9962b9-02f5-4860-a702-15a9d6b88f0a",
            "sourceColumn": "PeakHour Interactive Delay %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHour Interactive Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ba488ee9-ad40-43be-963b-6b6f99474e20",
            "sourceColumn": "PeakHour Interactive Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "PeakHour Background Rejection %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "974cb24b-7f3b-4b98-bf1a-d05944d52431",
            "sourceColumn": "PeakHour Background Rejection %",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "970722a1-64bb-408d-853f-629d79b51ef6",
        "partitions": [
          {
            "name": "TimePoint2CUDetail",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Timepoint",
            "source": {
              "expression": [
                "let",
                "Source = fnGetData(\"TimePointCUDetailForTridentV3\", null, null, \"14\"),",
                "#\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"WindowStartTime\", type datetime}, {\"WindowEndTime\", type datetime}}),",
                "        begintime= TimePoint2 - #duration(0,0,30,0),",
                "        endtime = TimePoint2 +  #duration(0,0,30,0),",
                "r = Table.SelectRows(#\"Changed Type1\", each [WindowStartTime] >= begintime and endtime > [WindowEndTime]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(r,{{\"CpuTimeMs\", Currency.Type}, {\"Interactive\", Currency.Type}, {\"Background\", Currency.Type}}),",
                "    #\"Divided Column\" = Table.TransformColumns(#\"Changed Type\", {{\"CpuTimeMs\", each _ / 1000, Currency.Type}}),",
                "    #\"Divided Column1\" = Table.TransformColumns(#\"Divided Column\", {{\"Interactive\", each _ / 1000, Currency.Type}}),",
                "    #\"Divided Column2\" = Table.TransformColumns(#\"Divided Column1\", {{\"Background\", each _ / 1000, Currency.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Divided Column2\",{{\"CpuTimeMs\", \"CUs\"}}),",
                "    #\"Divided Column3\" = Table.TransformColumns(#\"Renamed Columns\", {{\"InteractivePreview\", each _ / 1000, type number}}),",
                "    #\"Divided Column4\" = Table.TransformColumns(#\"Divided Column3\", {{\"BackgroundPreview\", each _ / 1000, type number}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Divided Column4\", \"CU Limit\", each 1),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"CU Limit\", type number}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DynamicColumnsTimepointInteractiveOperations",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e97b8e9cc33a41f88a20a09a3e0fc441"
          }
        ],
        "columns": [
          {
            "name": "Interactive Operation optional columns ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "03cc5d8e-0538-441b-ad74-daa34ce6ffc9",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Interactive Operation optional columns  Fields"
                }
              ]
            },
            "sortByColumn": "Interactive Operation optional columns  Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Interactive Operation optional columns  Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "18b243e7-a7ff-45fc-ba67-83d4c85e4c52",
            "sortByColumn": "Interactive Operation optional columns  Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Interactive Operation optional columns  Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "03738436-21da-4a3b-87bc-633ffcc90057",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "ee4cd437-52ea-4b69-8429-37e363cef863",
        "partitions": [
          {
            "name": "DynamicColumnsTimepointInteractiveOperations",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Billing type\", NAMEOF('TimePointInteractiveDetail'[Billing type]), 0),",
                "    (\"Virtualized item\", NAMEOF('Items'[IsVirtualArtifactName]), 1),",
                "    (\"Virtualized workspace\", NAMEOF('Items'[IsVirtualWorkspaceName]), 2),",
                "    (\"OperationId\", NAMEOF('TimePointInteractiveDetail'[OperationId]), 3),",
                "    (\"Smoothing start\", NAMEOF('TimePointInteractiveDetail'[Start]), 4),",
                "    (\"Smoothing end\", NAMEOF('TimePointInteractiveDetail'[End]), 5)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DynamicColumnsTimepointBackgroundOperations",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0779ae81b6ec4a649ce2495342b1cd37"
          }
        ],
        "columns": [
          {
            "name": "DynamicColumnsTimepointBackgroundOperations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "12a0b321-5f75-45e5-b83f-09119f5a7bbe",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "DynamicColumnsTimepointBackgroundOperations Fields"
                }
              ]
            },
            "sortByColumn": "DynamicColumnsTimepointBackgroundOperations Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DynamicColumnsTimepointBackgroundOperations Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "b893dbda-a9c9-48f0-a7a8-3d17c3a53632",
            "sortByColumn": "DynamicColumnsTimepointBackgroundOperations Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DynamicColumnsTimepointBackgroundOperations Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "1ed195a7-ea0f-497d-9624-8fed2afb0659",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "a40f69cc-a2f0-4e62-a2c0-6282a4e36fb4",
        "partitions": [
          {
            "name": "DynamicColumnsTimepointBackgroundOperations",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Billing type\", NAMEOF('TimePointBackgroundDetail'[Billing type]), 0),",
                "    (\"Virtualized item\", NAMEOF('Items'[IsVirtualArtifactName]), 1),",
                "    (\"Virtualized workspace\", NAMEOF('Items'[IsVirtualWorkspaceName]), 2),",
                "    (\"OperationId\", NAMEOF('TimePointBackgroundDetail'[OperationId]), 3),",
                "    (\"Smoothing start\", NAMEOF('TimePointBackgroundDetail'[Start]), 4),",
                "    (\"Smoothing end\", NAMEOF('TimePointBackgroundDetail'[End]), 5)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DynamicColumnsTimepoint2InteractiveOperations",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f79e315f25ed4fb0aac995b2515f9dbb"
          }
        ],
        "columns": [
          {
            "name": "DynamicColumnsTimepoint2InteractiveOperations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "ed20e322-edbf-4885-81ee-5ced16e42460",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "DynamicColumnsTimepoint2InteractiveOperations Fields"
                }
              ]
            },
            "sortByColumn": "DynamicColumnsTimepoint2InteractiveOperations Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DynamicColumnsTimepoint2InteractiveOperations Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "64a6c190-7a17-485a-bf2d-7380f5dc29e8",
            "sortByColumn": "DynamicColumnsTimepoint2InteractiveOperations Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DynamicColumnsTimepoint2InteractiveOperations Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "886a903b-26f2-428f-bfd5-11028a6894f3",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "cc98585b-6650-4a88-8bc9-fdaaa7757fc8",
        "partitions": [
          {
            "name": "DynamicColumnsTimepoint2InteractiveOperations",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Billing type\", NAMEOF('TimePoint2InteractiveDetail'[Billing type]), 0),",
                "    (\"Virtualized item\", NAMEOF('Items'[IsVirtualArtifactName]), 1),",
                "    (\"Virtualized workspace\", NAMEOF('Items'[IsVirtualWorkspaceName]), 2),",
                "    (\"OperationId\", NAMEOF('TimePoint2InteractiveDetail'[OperationId]), 3),",
                "    (\"Smoothing start\", NAMEOF('TimePoint2InteractiveDetail'[Start]), 4),",
                "    (\"Smoothing end\", NAMEOF('TimePoint2InteractiveDetail'[End]), 5)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DynamicColumnsTimepoint2BackgroundOperations",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "18f36a840b77493084acc9ea344443f1"
          }
        ],
        "columns": [
          {
            "name": "DynamicColumnsTimepoint2BackgroundOperations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "0e11f94f-2651-43a8-b189-9d5195a7fb0b",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "DynamicColumnsTimepoint2BackgroundOperations Fields"
                }
              ]
            },
            "sortByColumn": "DynamicColumnsTimepoint2BackgroundOperations Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DynamicColumnsTimepoint2BackgroundOperations Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "6ec2bed3-96b1-40c0-a8b1-01ae30d3d318",
            "sortByColumn": "DynamicColumnsTimepoint2BackgroundOperations Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DynamicColumnsTimepoint2BackgroundOperations Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "0c9d2379-32b1-4bad-97d6-21275ca5ae9b",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "52573ce4-39e3-4a39-b71f-f57b1ba307cf",
        "partitions": [
          {
            "name": "DynamicColumnsTimepoint2BackgroundOperations",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Billing type\", NAMEOF('TimePoint2BackgroundDetail'[Billing type]), 0),",
                "    (\"Virtualized item\", NAMEOF('Items'[IsVirtualArtifactName]), 1),",
                "    (\"Virtualized workspace\", NAMEOF('Items'[IsVirtualWorkspaceName]), 2),",
                "    (\"OperationId\", NAMEOF('TimePoint2BackgroundDetail'[OperationId]), 3),",
                "    (\"Smoothing start\", NAMEOF('TimePoint2BackgroundDetail'[Start]), 4),",
                "    (\"Smoothing end\", NAMEOF('TimePoint2BackgroundDetail'[End]), 5)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "MaxMemoryByItemAndHour",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ItemId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "f7980ded-4ac5-435c-91f0-7681c8dafdcb",
            "sourceColumn": "ItemId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Item Size (GB)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b6007328-92c4-4884-8807-47e0056756f2",
            "sourceColumn": "Item Size (GB)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "SkuMemory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e176d65-73c1-48ff-b5fb-a701cf78795e",
            "sourceColumn": "SkuMemory",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a3a5b63-9d98-425d-82f1-e1062909f2d9",
            "sourceColumn": "PremiumCapacityId",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "ItemKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e830435-1f57-4188-8a5f-f59bbc6696e9",
            "sourceColumn": "ItemKey",
            "summarizeBy": "none"
          },
          {
            "name": "Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4f574aeb-4ea1-4539-941c-6717b1e6fc2d",
            "sourceColumn": "Timestamp",
            "sourceProviderType": "datetimeoffset",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4358c283-63f9-482f-96b0-d3f1729a93c9",
        "partitions": [
          {
            "name": "MaxMemoryByItemAndHour",
            "mode": "directQuery",
            "queryGroup": "Direct Query\\Performance",
            "source": {
              "expression": [
                "let",
                "    Source = fnGetData(\"MaxMemoryByArtifactAndHour\"),",
                "    #\"Uppercased Text\" = Table.TransformColumns(Source,{{\"ArtifactId\", Text.Upper, type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Uppercased Text\",{{\"ArtifactId\", \"ItemId\"}, {\"Artifact Size (GB)\", \"Item Size (GB)\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"ItemKey\", each [PremiumCapacityId]&[ItemId])",
                "in ",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}