CREATE VIEW dbo.vwDimSuppliedPart
AS
SELECT TOP (1000) [SuppliedPartKey]
      ,[PartCode]
      ,[SupplierCode]
      ,[SuppliedPartQuantity]
      ,[SuppliedPartCost]
      ,[SuppliedPartComment]
      ,[PartName]
      ,[PartManufacturer]
      ,[PartBrand]
      ,[PartType]
      ,[PartSize]
      ,[PartContainer]
      ,[PartRetailPrice]
      ,[PartComment]
      ,[CreateDatetime]
      ,[ChangeDatetime]
      ,[LoadId]
  FROM [dbo].[DimSuppliedPart]