CREATE VIEW dbo.vwFactOrderLines
AS
SELECT TOP (1000) [CommitDateKey]
      ,[CustomerKey]
      ,[OrderDateKey]
      ,[ReceiptDateKey]
      ,[ShipDateKey]
      ,[SuppliedPartKey]
      ,[SupplierKey]
      ,[OrderCode]
      ,[LineNumber]
      ,[Quantity]
      ,[ExtendedPrice]
      ,[Discount]
      ,[Tax]
      ,[ReturnFlag]
      ,[LineStatus]
      ,[ShipInstruct]
      ,[ShipMode]
      ,[LineItemComment]
      ,[OrderStatus]
      ,[OrderTotalPrice]
      ,[OrderPriority]
      ,[OrderClerk]
      ,[OrderShipPriority]
      ,[OrderComment]
      ,[LoadId]
  FROM [dbo].[FactOrderLines]
;